aquaproj/aqua

.github/workflows/test-release.yaml
It takes a long time to build, so in CI of the pull request let's stop building unless the build configuration is updated.
=> ci: add test-release

pkg/controller/config.go, pkg/controller/exec.go
=> fix: support global config file name `[.]aqua.y[a]ml`

cmd/aqua/main.go, pkg/controller/controller.go, pkg/controller/download.go, pkg/controller/exec.go, pkg/controller/install.go, pkg/controller/install_proxy.go, pkg/controller/unarchive.go, pkg/log/log.go
aqua is called transparently.
Add `"program": "aqua"` to log of aqua for users to find that the source of log is `aqua`.
e.g.
```console
$ fzf --version
INFO[0000] create a symbolic link                        link_file=/workspace/.aqua/bin/fzf new=/root/.aqua/bin/aqua-proxy program=aqua
0.27.2 (e086f0b)
```
=> feat: add "program": "aqua" to log

cmd/aqua/main.go
Same as https://github.com/suzuki-shunsuke/aqua-proxy/pull/7
Note that this fix doesn't work for Windows.
https://pkg.go.dev/os#Signal
> The only signal values guaranteed to be present in the os package on all systems are os.Interrupt (send the process an interrupt) and os.Kill (force the process to exit).
> On Windows, sending os.Interrupt to a process with os.Process.Signal is not implemented;
> it will return an error instead of sending a signal.
=> fix: handle SIGTERM

docs/config.md, pkg/controller/config.go, pkg/controller/download.go, pkg/controller/download_github.go, pkg/controller/download_url.go, pkg/controller/exec.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go, pkg/controller/install.go, pkg/controller/install_proxy.go
Close #5
e.g. helm
```yaml
packages:
- name: helm
registry: inline
version: v3.6.3 # renovate: depName=helm/helm
inline_registry:
- name: helm
type: http
url: https://get.helm.sh/helm-{{.Package.Version}}-{{.OS}}-{{.Arch}}.tar.gz
files:
- name: helm
src: "{{.OS}}-{{.Arch}}/helm"
```
```
$ tree ~/.aqua/pkgs/http 
~/.aqua/pkgs/http
└── get.helm.sh
└── helm-v3.6.3-darwin-amd64.tar.gz
└── darwin-amd64
├── LICENSE
├── README.md
└── helm
3 directories, 3 files
```
=> feat: support HTTP

README.md, docs/config.md, docs/registry.md, pkg/controller/config.go, pkg/controller/exec.go, pkg/controller/install.go, pkg/controller/install_packages.go, pkg/controller/registry.go, pkg/controller/unarchive.go, pkg/controller/util.go
Close #7
Support `github_content` Registry.
aqua.yaml
```yaml
packages:
- name: golangci-lint
registry: official
version: v1.42.0 # renovate: depName=golangci/golangci-lint
registries:
- name: official
type: github_content
repo_owner: suzuki-shunsuke
repo_name: aqua-registry
ref: v0.1.1-0
path: registry.yaml
```
https://github.com/suzuki-shunsuke/aqua-registry
=> feat: support Registry

README.md, aqua.yaml, docs/config.md, pkg/controller/config.go, pkg/controller/registry.go, tutorial/aqua.yaml, tutorial/docker-compose.yml
BREAKING CHANGE: `inline_registry`'s structure is changed
The field `packages` is added.
AS IS
```yaml
inline_registry:
- name: jq
repo_owner: stedolan
repo_name: jq
asset: 'jq-{{if eq .OS "darwin"}}osx{{else}}{{.OS}}{{end}}-{{.Arch}}'
files:
- name: jq
```
TO BE
```yaml
inline_registry:
packages:
- name: jq
repo_owner: stedolan
repo_name: jq
asset: 'jq-{{if eq .OS "darwin"}}osx{{else}}{{.OS}}{{end}}-{{.Arch}}'
files:
- name: jq
```
=> feat: change the inline registry structure

pkg/controller/config.go, pkg/controller/registry.go
Follow up #158
```
bash-5.1# aqua install
FATA[0000] aqua failed                                   error="configuration is invalid: Key: 'Config.InlineRegistry' Error:Field validation for 'InlineRegistry' failed on the 'dive' tag" program=aqua
```
https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Dive
=> fix: fix validator tag "dive"

pkg/controller/generate.go
Close #218
https://pkg.go.dev/github.com/ktr0731/go-fuzzyfinder#WithPreviewWindow
> If there is no selected item, previewFunc passes -1 to previewFunc.
=> fix: handle the negative index of `previewFunc`

pkg/controller/config.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go, pkg/controller/replacements.go
e.g.
```yaml
inline_registry:
packages:
- name: accurics/terrascan
repo_owner: accurics
repo_name: terrascan
asset: 'terrascan_{{trimPrefix "v" .Package.Version}}_{{title .OS}}_{{.Replacements.Arch}}.tar.gz'
files:
- name: terrascan
replacements:
amd64: x86_64
- name: fujiwara/lambroll
repo_owner: fujiwara
repo_name: lambroll
archive_type: tar.gz
archive_type_overrides:
- goos: darwin
archive_type: zip
asset: 'lambroll_{{.Package.Version}}_{{.OS}}_{{.Arch}}.{{.PackageInfo.GetArchiveType}}'
files:
- name: lambroll
src: lambroll_{{.Package.Version}}_{{.OS}}_{{.Arch}}/lambroll
packages:
- name: accurics/terrascan
registry: inline
version: v1.9.0
- name: fujiwara/lambroll
registry: inline
version: v0.11.8
```
=> feat: support replacements

pkg/cli/install.go, pkg/cli/list.go, pkg/cli/runner.go, pkg/controller/config.go, pkg/controller/generate.go, pkg/controller/list.go
```
$ aqua list
```
```
$ aqua list | aqua g -f -
```
`aqua generate` is changed.
You can't select the version interactively.
Instead of selecting the version, the latest version except for prereleases is gotten automatically.
=> feat: add list command and generate's `-f` option

pkg/controller/github_release_package.go
Close #272
* default package name: `<repo owner>/<repo name>`
* default link: `https://github.com/<repo owner>/<repo name>`
=> feat: set the default package name and link to `github_release` package

docs/config.md, pkg/controller/config.go, pkg/controller/download.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go, pkg/controller/unarchive.go
Close #269
⚠️ BREAKING CHANGE; `archive_type` and `archive_type_overrides` are renamed
Set the default `files` of `github_release` package.
The default value is
```yaml
files:
- name: <repo name>
```
=> feat: replace `archive_type` to `format` and set the default `files` of `github_release` package

docs/registry_config.md, go.mod, go.sum, pkg/controller/config.go, pkg/controller/exec.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go, pkg/controller/install_packages.go, pkg/controller/version_constraint.go
Close #21
Some package attributes like `asset` and `files` may be different by it's version.
For example, the asset structure of [golang-migrate](https://github.com/golang-migrate/migrate) was changed from v4.15.0.
In that case, the attributes `version_constraint` and `version_overrides` are useful.
e.g.
```yaml
repo_owner: golang-migrate
repo_name: migrate
asset: 'migrate.{{.OS}}-{{.Arch}}.tar.gz'
description: Database migrations. CLI and Golang library
version_constraint: 'semver("> 4.14.1")'
version_overrides:
- version_constraint: 'semver("<= 4.14.1")'
files:
- name: migrate
src: 'migrate.{{.OS}}-{{.Arch}}'
```
`version_constraint` is [expr](https://github.com/antonmedv/expr)'s expression.
The evaluation result must be a boolean.
Currently, the following values …
=> feat: support changing package info per version

pkg/controller/install.go
Close #331
When `aqua i` command's `-c` option isn't set, aqua finds the configuration file from the current directory to the root directory.
When `aqua i` command's `-a` option is set, `aqua i` should not fail even if the configuration file isn't found.
=> fix: when `-a` option is set, the error file isn't found is ignored

pkg/controller/config.go, pkg/controller/generate.go
Follow up #334
e.g.
```console
$ echo standard,kubernetes/kubectl | aqua g -f -
- name: kubernetes/kubectl
registry: standard
version: '[SET PACKAGE VERSION]'
```
```console
$ echo standard,ahmetb/kubectl-tree | aqua g -f -
- name: ahmetb/kubectl-tree@v0.4.1
registry: standard
```
=> feat: generate code with new syntax

.github/workflows/integration-test.yaml, pkg/controller/generate.go
Follow up #342
Fix the generation of `github_content` type's package configuration by `aqua g` command.
* Get the latest version
* Use the new syntax
AS IS
```console
$ echo "standard,suzuki-shunsuke/aqua-installer" | aqua g -f -
- name: suzuki-shunsuke/aqua-installer
version: '[SET PACKAGE VERSION]'
```
TO BE
```console
$ echo "standard,suzuki-shunsuke/aqua-installer" | aqua g -f -
- name: suzuki-shunsuke/aqua-installer@v0.1.3
```
=> fix: generate `github_content` package's configuration with new syntax

pkg/cli/exec.go, pkg/cli/which.go, pkg/controller/error.go, pkg/controller/exec.go, pkg/controller/which.go
The code of `which` and `exec` are duplicated, so let's merge them.
=> refactor: merge code of exec and which command

aqua.yaml, aqua/reviewdog.yaml, docs/config.md, pkg/controller/config.go
Close #382
e.g.
Directory structure
```
aqua.yaml
aqua/
conftest.yaml
```
aqua.yaml
```yaml
registries:
- type: standard # standard registry
ref: v0.10.5 # renovate: depName=suzuki-shunsuke/aqua-registry
- import: aqua/*.yaml
```
aqua/conftest.yaml
```yaml
packages:
- name: open-policy-agent/conftest@v0.28.2
```
`import` is useful for CI.
You can execute test and lint only when the specific package is updated.
ex. GitHub Actions' [`on.<push|pull_request>.paths`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths)
```yaml
name: conftest
on:
pull_request:
paths:
- policy/**.rego
- aqua/conftest.yaml
```
=> feat: support splitting packages definition

pkg/controller/download_github.go
Close #388
I have tested if downloading assets from public repository's GitHub Releases anonymously is rate limited.
As a result of test, it seems not to be limited.
So at first aqua tries to download assets without GitHub API.
And if it failed, aqua tries again with GitHub API.
It avoids the rate limit of GitHub API.
=> feat: download assets from public repository's GitHub Release without GitHub API

pkg/controller/install_packages.go, pkg/controller/install_proxy.go
=> fix: failed to create a symbolic link to aqua-proxy: file exists

pkg/controller/package_info.go, pkg/controller/unarchive.go
Close #408
If you have already installed `github_content` packages, you may have to reinstall them.
```console
$ dgoss --help
WARN[0000] check file_src is correct                     aqua_version= error="exe_path isn't found: stat ~/.aqua/pkgs/github_content/github.com/aelsabbahy/goss/v0.3.16/extras/dgoss/dgoss/dgoss: no such file or directory" file_name=dgoss package_name=aelsabbahy/goss/dgoss package_version=v0.3.16 program=aqua registry=standard
```
Remove `github_content` packages at once.
e.g.
```
$ rm -R ~/.aqua/pkgs/github_content
```
=> fix: fix `github_content` package's install path

renovate.json5
The document has been migrated to https://github.com/aquaproj/aquaproj.github.io
=> chore: remove outdated Renovate config

pkg/controller/config.go, pkg/controller/package_info.go
=> feat: add the field `rosetta2` to support Rosetta 2 easily

pkg/controller/generate.go
Sometimes installed command names aren't included in the package name, so you can't search package with the command name.
And you can't know what commands are installed by the package.
Add command names in the result of `aqua g`.
e.g.
```
aquasecurity/starboard (standard) (starboard, kubectl-starboard)           ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
int128/kauthproxy (standard) (kauthproxy, kubectl-auth_proxy)              │  kubernetes/kubectl
aquasecurity/kubectl-who-can (standard) (kubectl-who_can)                  │
argoproj/argo-rollouts (standard) (kubectl-argo-rollouts)                  │  https://kubernetes.io/docs/reference/kubectl/overview/
corneliusweig/ketall (standard) (ketall, kubectl-get_all)                  │  The kubectl command line …
```
=> feat: add command names in the result of `aqua g`

.github/workflows/integration-test.yaml, pkg/cli/runner.go, pkg/controller/generate.go
When you pass the list of packages to `aqua g`, you can omit the registry name if the registry name is `standard`.
```console
$ echo "suzuki-shunsuke/tfcmt" | aqua g -f -
FATA[0000] aqua failed                                   aqua_version=0.8.7 error="unknown package" package_name=suzuki-shunsuke/tfcmt program=aqua
$ echo "standard,suzuki-shunsuke/tfcmt" | aqua g -f -
- name: suzuki-shunsuke/tfcmt@v3.0.0
```
```console
$ echo "suzuki-shunsuke/tfcmt" | aqua g -f -
- name: suzuki-shunsuke/tfcmt@v3.0.0
$ echo "standard,suzuki-shunsuke/tfcmt" | aqua g -f -
- name: suzuki-shunsuke/tfcmt@v3.0.0
```
=> feat: support omitting the registry name

.github/workflows/integration-test.yaml, pkg/cli/generate.go, pkg/cli/runner.go, pkg/controller/generate.go
Close #484
You can pass packages with positional arguments.
```console
$ aqua g [<registry name>,<package name> ...]
```
```console
$ aqua g standard,cli/cli standard,junegunn/fzf
- name: cli/cli@v2.2.0
- name: junegunn/fzf@0.28.0
```
You can omit the registry name if it is "standard".
```console
$ aqua g cli/cli
- name: cli/cli@v2.2.0
```
=> feat: support passing packages with `aqua g`'s arguments

pkg/controller/error.go, pkg/controller/validate.go, pkg/controller/validate_internal_test.go
In aqua.yaml, when the pair of the registry and package is duplicated, aqua fails to read the configuration.
```yaml
registries:
- type: standard
ref: v0.12.2 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/tfcmt@v3.0.0
- name: suzuki-shunsuke/tfcmt@v2.0.0
```
```
$ aqua i
FATA[0000] aqua failed                                   aqua_version=0.8.8 error="configuration is invalid: the pair of package name and registry must be unique" package_name=suzuki-shunsuke/tfcmt program=aqua retistry_name=standard
```
=> fix: allow to install same pair of the registry name and package name

pkg/controller/generate.go
https://github.com/aquaproj/aqua-renovate-config/releases/tag/0.1.3
AS IS
```console
$ aqua g istio/istio/istioctl
- name: istio/istio/istioctl
version: 1.12.1
```
TO BE
```console
$ aqua g istio/istio/istioctl
- name: istio/istio/istioctl@1.12.1
```
=> feat: output with short syntax if package name starts with `<repository full name>/"

pkg/controller/package_info.go, pkg/controller/package_info_test.go
```console
$ aqua g hashicorp/terraform
- name: hashicorp/terraform
version: '[SET PACKAGE VERSION]'
```
```console
$ aqua g hashicorp/terraform
- name: hashicorp/terraform@v1.1.2
```
=> feat: support getting the version of `http` package in `aqua g`

pkg/controller/init.go
Change file mode of aqua.yaml (which is placed on `aqua init`) from 755 to 644 since it is just a configuration file but not executable 💪
=> fix: treat aqua.yaml which places on init as normal file rather than executable

.github/workflows/integration-test.yaml, .github/workflows/test.yaml, pkg/controller/config.go, pkg/controller/controller.go, pkg/controller/install.go, pkg/controller/which.go
* File paths are changed
* Default Global Configuration `$AQUA_ROOT_DIR/global` is removed. If you use Global Configuration, please set `$AQUA_GLOBAL_CONFIG`.
Note that Global Configuration file is optional.
* aqua installs tools in `$AQUA_ROOT_DIR`
* You have to add `${AQUA_ROOT_DIR}/bin` to `$PATH`
* Global Configuration file is located at `${AQUA_ROOT_DIR}/global`
* Default value of `$AQUA_ROOT_DIR` is `$HOME/.aqua`
* aqua installs tools in `$AQUA_ROOT_DIR`: No change
* You have to add `${AQUA_ROOT_DIR}/bin` to `$PATH`: No change
* Default Global Configuration file is removed
* Default value of `$AQUA_ROOT_DIR` is `${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua`
=> feat: support XDG Base Directory by default

.golangci.yml, aqua.yaml, pkg/controller/generate_insert.go
When `packages:` is empty, `aqua g -i` ignores the ident of `registries`.
aqua.yaml
```yaml
---
registries:
- type: standard
ref: v1.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
```
```console
$ aqua g -i cli/cli
```
```yaml
---
registries:
- type: standard
ref: v1.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.5.1
```
```yaml
---
registries:
- type: standard
ref: v1.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.5.1
```
=> fix: fix `aqua g -i`

pkg/controller/registry.go
This rolls back the change in yaml modules for reading the registries. resolves #582 
```
─❯ time ./aqua.out which actionlint >/dev/null
________________________________________________________
Executed in   19.76 millis    fish           external
usr time   19.89 millis  768.00 micros   19.12 millis
sys time    4.91 millis  137.00 micros    4.77 millis
```
=> use yaml.v2 for registry parsing

pkg/cli/runner.go, pkg/controller/finder.go, pkg/controller/generate.go
```console
$ aqua g
```
You can select multiple packages by tab key.
This feature is powered by [go-fuzzyfinder#FindMulti](https://pkg.go.dev/github.com/ktr0731/go-fuzzyfinder#FindMulti).
=> feat: support selecting multiple packages by tab key in `aqua g`'s fuzzy finder

.github/workflows/integration-test.yaml, pkg/config/override.go, pkg/config/package_info.go, pkg/config/package_info_internal_test.go, pkg/config/package_info_test.go, pkg/config/replacements.go, pkg/config/version_override.go, pkg/controller/which/which.go, pkg/installpackage/installer.go, tests/aqua-global.yaml, tests/registry.yaml
Close #607
This adds `overrides` in Registry Configuration. https://aquaproj.github.io/docs/reference/registry-config
You can override the following attributes on the specific `GOOS` and `GOARCH`.
* replacements
* format
* asset
* url
* files
e.g. On Linux ARM64, `Arch` becomes `aarch64`.
```yaml
overrides:
- goos: linux
replacements:
arm64: aarch64
```
In case of `replacements`, maps are merged.
Either `goos` or `goarch` is required.
e.g.
```yaml
asset: arkade
overrides:
- goos: linux
goarch: arm64
asset: 'arkade-{{.Arch}}'
- goos: darwin
goarch: amd64
asset: 'arkade-darwin'
- goos: darwin 
asset: 'arkade-darwin-{{.Arch}}'
```
Even if multiple elements are matched, only first element is applied.
For example, Darwin AMD64 matches with second element but the second element isn't applied …
=> feat: support `overrides`

README.md
This versioning policy is for v0.x.
aqua v1 has already been released, so the description about versioning
policy isn't needed.
=> docs: remove versioning policy

pkg/config/config.go, pkg/config/override.go, pkg/config/package_info.go, pkg/config/package_info_test.go, pkg/config/replacements.go, pkg/controller/which/which.go, pkg/controller/which/which_internal_test.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/download/download.go, pkg/download/public.go, pkg/installpackage/installer.go, pkg/installpackage/proxy.go, pkg/installpackage/public.go, pkg/runtime/runtime.go, pkg/version-constraint/package_condition.go
Close #643
⚠️ This feature is only for aqua registry's developers.
If you don't write aqua registry, please ignore this.
Set the environment variable `AQUA_GOOS` and `AQUA_GOARCH`.
```console
$ AQUA_GOOS=darwin AQUA_GOARCH=arm64 aqua i
$ AQUA_GOOS=darwin AQUA_GOARCH=arm64 aqua which gh
```
```console
$ go run ./cmd/aqua which gh
/Users/shunsuke-suzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/cli/cli/v2.8.0/gh_2.8.0_macOS_amd64.tar.gz/gh_2.8.0_macOS_amd64/bin/gh
$ AQUA_GOOS=linux go run ./cmd/aqua which gh
/Users/shunsuke-suzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/cli/cli/v2.8.0/gh_2.8.0_linux_amd64.tar.gz/gh_2.8.0_linux_amd64/bin/gh
$ AQUA_GOOS=linux AQUA_GOARCH=arm64 go run ./cmd/aqua which gh …
```
=> feat: support changing GOOS and GOARCH for testing

json-schema/registry.json, pkg/config/config.go, pkg/config/package_info.go, pkg/controller/generate/finder.go, pkg/controller/generate/generate.go, tests/aqua-global.yaml, tests/registry.yaml
Close #674
aqua.yaml
```yaml
---
registries:
- type: local
name: local
path: registry.yaml
packages:
- name: ahmetb/kubens
registry: local
version: v0.9.4
```
registry.yaml
```yaml
packages:
- name: ahmetb/kubectx/kubens
aliases:
- name: ahmetb/kubens
repo_owner: ahmetb
repo_name: kubectx
asset: "kubens_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}"
description: Faster way to switch between clusters and namespaces in kubectl
files:
- name: kubens
replacements:
386: i386
amd64: x86_64
format: tar.gz
format_overrides:
- goos: windows
format: zip
```
```console
$ aqua list
local,ahmetb/kubectx/kubens
```
```console
$ aqua g local,ahmetb/kubens
- name: ahmetb/kubectx/kubens@v0.9.4
registry: local
```
```console
$ kubens -V
0.9.4
```
```console
$ aqua i
INFO[0000] download …
```
=> feat: support aliases

pkg/config/registry_test.go, pkg/install-registry/install.go, pkg/template/template.go, pkg/version-constraint/package_condition.go, pkg/version-constraint/version_constraint.go, pkg/version-constraint/version_filter.go
Close #677
Compare JSON with YAML.
```console
$ go test -bench . -benchmem
goos: darwin
goarch: arm64
pkg: github.com/aquaproj/aqua/pkg/config
BenchmarkReadRegistry/yaml-8         	     198	   5812580 ns/op	 2613083 B/op	   59282 allocs/op
BenchmarkReadRegistry/json-8         	     588	   1711825 ns/op	 1087863 B/op	   10940 allocs/op
PASS
ok  	github.com/aquaproj/aqua/pkg/config	5.779s
```
JSON is much faster than YAML.
https://github.com/sharkdp/hyperfine
```console
$ hyperfine --version
hyperfine 1.13.0
```
```yaml
---
registries:
- type: local
name: local
path: registry.json # registry.yaml
packages:
- name: suzuki-shunsuke/tfcmt@v3.2.1
registry: local
```
```console
$ hyperfine -N --warmup 3 'tfcmt -v' '/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/su …
```
=> perf: support JSON as Registry Configuration

pkg/config/override.go, pkg/config/package_info.go, pkg/config/package_info_internal_test.go, pkg/config/version_override.go, pkg/controller/which/which.go, pkg/installpackage/installer.go
Close #694
I've confirmed that the bug has been fixed.
```console
$ aqua i                                                                                                
INFO[0000] download and unarchive the package            aqua_version= package_name=Arriven/db1000n package_version=v0.8.19 program=aqua registry=standard registry_ref=v2.11.1
INFO[0000] download and unarchive the package            aqua_version= package_name=Arriven/db1000n package_version=v0.8.33 program=aqua registry=standard registry_ref=v2.11.1
```
=> fix: copy PackageInfo instead of updating

pkg/log/log.go
e.g.
```
DEBU[0000] check the permission                          aqua_version= env=darwin/arm64 file_name=golangci-lint package_name=golangci/golangci-lint package_version=v1.46.2 program=aqua registry=standard registry_ref=v2.16.0
```
```
env=darwin/arm64
```
=> feat: add the information about runtime to log

pkg/controller/generate/finder.go
=> fix: prevent a panic when no package matches in aqua g's fuzzy finder

.github/workflows/integration-test.yaml, pkg/config/config.go, pkg/config/package_info.go, pkg/controller/exec/exec_test.go, pkg/controller/install/install_test.go, pkg/controller/which/which.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/download/download.go, pkg/exec/exec.go, pkg/installpackage/installer.go, pkg/installpackage/installer_test.go, pkg/installpackage/proxy_test.go, pkg/installpackage/public.go, tests/aqua-global.yaml, tests/registry.yaml
Close #798
registry.yaml
```yaml
packages:
- type: go
repo_owner: mitchellh
repo_name: gox
description: A dead simple, no frills Go cross compile tool
files:
- name: gox
dir: "gox-{{trimV .Version}}"
```
aqua.yaml
```
registries:
- name: standard
type: local
path: registry.yaml
packages:
- name: mitchellh/gox@v1.0.1
```
```console
$ aqua i                                                 
INFO[0000] create a symbolic link                        aqua_version= env=darwin/arm64 link_file=/Users/shunsukesuzuki/.local/share/aquaproj-aqua/bin/gox new=aqua-proxy package_name=mitchellh/gox package_version=v1.0.1 program=aqua registry=standard
INFO[0000] download and unarchive the package            aqua_version= env=darwin/arm64 package_name=mitchellh/gox package_version=v1.0.1 program=aqua …
```
=> feat: support building Go tool to install

tests/registry.yaml
=> ci: test unknown type package

.github/workflows/integration-test.yaml, pkg/controller/generate/generate_test.go, pkg/controller/initcmd/init_test.go, pkg/download/download.go, pkg/download/download_test.go, pkg/download/registry_test.go, pkg/github/github.go, pkg/github/mock.go, tests/aqua-global.yaml
Close #812
e.g. aqua.yaml
```yaml
- name: mitchellh/gox
registry: local
version: 8c3b2b9e647dc52457d6ee7b5adcf97e2bafe131
- name: bats-core/bats-core
version: 9695e7c589a07756c999893764ccd9a506a47f89
```
=> feat: support specifying revision as version for github_archive and go package

pkg/cli/exec.go, pkg/cli/generate.go, pkg/cli/init.go, pkg/cli/install.go, pkg/cli/list.go, pkg/cli/profile.go, pkg/cli/runner.go, pkg/cli/trace.go, pkg/cli/which.go
Add global command line options `-trace` and `-cpu-profile`.
This is useful for the performance tuning.
The following Go's standard libraries are used.
* https://pkg.go.dev/runtime/trace
* https://pkg.go.dev/runtime/pprof
All sub commands except for `help` and `version` commands support this option.
```console
$ aqua -trace trace.out exec -- gh version # a file trace.out is created
$ go tool trace trace.out
2022/06/01 11:18:47 Parsing trace...
2022/06/01 11:18:47 Splitting trace...
2022/06/01 11:18:47 Opening browser. Trace viewer is listening on http://127.0.0.1:58380
```
```console
$ aqua -cpu-profile pprof.out exec -- gh version # a file pprof.out is created
$ go tool pprof -http=":8000" "$(which aqua)" pprof.out
```
=> feat: add global command line options `-trace` and `-cpu-profile` for tracing and CPU Profiling

pkg/controller/which/lookpath.go
https://pkg.go.dev/path/filepath#SplitList
=> fix: use filepath.SplitList instead of strings.Split

pkg/config/package.go, pkg/config/package_info_test.go
=> feat: add the file extension ".exe" to asset names if GOOS is "windows" and the asset format is "raw"

pkg/controller/install/install_test.go, pkg/installpackage/proxy.go, pkg/installpackage/proxy_test.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.1.2
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.1.1
=> chore: update aqua-proxy from v1.1.0 to v1.1.2

.github/workflows/integration-test.yaml, pkg/cli/completion.go, pkg/cli/runner.go
Fix #856
With this fix, now you can add the following line to `.bashrc` to enable commands completion for aqua.
```
if which aqua &> /dev/null; then source <(aqua completion bash); fi
```
=> feat: add 'completion bash|zsh' commands

go.mod, go.sum, pkg/config/root_dir_windows.go
Close https://github.com/aquaproj/aqua/issues/887
Change the default path of AQUA_ROOT_DIR on Windows from `~/.local/share/aquaproj-aqua` to `~/AppData/Local/aquaproj-aqua`.
=> fix: change the default path of AQUA_ROOT_DIR on Windows

pkg/controller/install/install.go, pkg/controller/install/install_test.go, pkg/controller/wire_gen.go, pkg/installpackage/installer.go, pkg/installpackage/link.go, pkg/installpackage/proxy.go
=> feat: replace symbolic links to executable proxy file on Windows

pkg/cli/generate.go, pkg/cli/runner.go, pkg/config/package.go, pkg/config/registry/package_info.go, pkg/controller/generate/generate.go, pkg/controller/generate/generate_test.go, pkg/controller/generate/version_selector.go, pkg/controller/generate/version_selector_internal_test.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/github/github.go
Close #955
```console
$ aqua g -s cli/cli
```
You can select a version with a fuzzy finder.
=> Support selecting a version interactively in `aqua g` command

pkg/controller/generate/finder.go
```console
aqua g -s cli/cli
```
=> fix(generate): improve newlines in the fuzzy finder's preview

go.mod, go.sum, pkg/download/download.go, pkg/download/download_github.go, pkg/download/download_test.go, pkg/download/download_url.go, pkg/download/download_url_internal_test.go, pkg/download/public.go, pkg/download/registry.go, pkg/installpackage/download.go, pkg/unarchive/decompressor.go, pkg/unarchive/raw.go, pkg/unarchive/unarchive.go, pkg/unarchive/unarchive_test.go, pkg/unarchive/unarchiver.go
Close #956
Powered by [github.com/schollz/progressbar/v3](https://pkg.go.dev/github.com/schollz/progressbar/v3).
```console
$ aqua i
INFO[0000] download and unarchive the package            aqua_version= env=darwin/arm64 package_name=aqua-proxy package_version=v1.1.2 program=aqua registry=
Downloading aqua-proxy v1.1.2 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████| (668/668 kB, 11.270 MB/s)
INFO[0000] create a symbolic link                        aqua_version= env=darwin/arm64 link_file=/Users/shunsukesuzuki/Documents/test/aqua/progress/aquaproj-aqua/bin/aqua-proxy new=../pkgs/github_release/github.com/aquaproj/aqua-proxy/v1.1.2/aqua-proxy_darwin_arm64.tar.gz/aqua-proxy package_name=aqua-proxy package_version=v1.1.2 …
```
=> feat: show progress bars when tools are being installed

pkg/controller/generate-registry/arch.go, pkg/controller/generate-registry/os.go
"unknown-linux-musl" and "pc-windows-msvc" take precedence over "unknown-linux-gnu" and "pc-windows-gnu"
=> fix(generate-registry): fix replacements

pkg/config/registry/package_info.go, pkg/controller/generate/finder.go, pkg/controller/generate/finder_internal_test.go, tests/registry.yaml
* Omit the registry name if the name is `standard`
* Add the field `search_words` to improve the interactive search
AS IS
```
<package name> (<aliase>, ...) (<registry name>) (command name, ...)
```
TO BE
```
<package name> (<aliase>, ...) (<registry name>) [command name, ...]: <search word> ...
```
=> feat(generate): improve items

.github/workflows/integration-test.yaml, pkg/cli/runner.go, pkg/config/package.go, pkg/installpackage/download.go, pkg/installpackage/installer.go, pkg/installpackage/public.go
Close #976
The progress bar is disabled by default, but you can enable it by setting the environment variable `AQUA_PROGRESS_BAR` to `true`.
```console
$ export AQUA_PROGRESS_BAR=true
```
=> fix: disable the progress bar by default

.github/workflows/integration-test.yaml, pkg/cli/runner.go, pkg/config/package.go, pkg/log/log.go
Close #982
Support setting the log coloring by the environment variable `AQUA_LOG_COLOR`.
```console
$ export AQUA_LOG_COLOR=always|auto|never
```
=> feat: support setting log coloring

pkg/controller/generate/generate.go
=> fix(generate): suppress outputting an empty array

pkg/controller/generate/generate.go
Fix typo in `aqua generate` output
Signed-off-by: Noel Georgi <git@frezbo.dev>
=> fix: typo in output

pkg/installpackage/checksum.go
checksum is case insensitive.
https://github.com/aquaproj/aqua-registry/pull/6159#issuecomment-1243406844
=> fix: normalize checksum

pkg/installpackage/link.go
Replace log fields `link_file` and `new` to `command`.
AS IS
```
$ aqua i
INFO[0000] create a symbolic link                        aqua_version= env=darwin/arm64 link_file=/Users/shunsukesuzuki/.local/share/aquaproj-aqua/bin/actionlint new=aqua-proxy program=aqua
```
```
$ aqua i
INFO[0000] create a symbolic link                        aqua_version= command=actionlint env=darwin/arm64 program=aqua
```
=> fix: improve a log creating a symbolic link

pkg/config-reader/reader.go, pkg/config/aqua/config.go, pkg/config/registry/config.go, pkg/install-registry/install.go, tests/aqua.yaml
=> fix: ignore nil elements to avoid panic

.github/workflows/integration-test.yaml, pkg/cli/cp.go, pkg/controller/cp/controller.go, pkg/controller/install/install.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/domain/package_installer.go, pkg/installpackage/installer.go, pkg/installpackage/public.go
Close #1173
```console
$ aqua cp
INFO[0000] copying an executable file                    aqua_version= env=darwin/arm64 file_name=cmdx package_name=suzuki-shunsuke/cmdx package_version=v1.6.1 program=aqua registry=standard
INFO[0000] copying an executable file                    aqua_version= env=darwin/arm64 file_name=actionlint package_name=rhysd/actionlint package_version=v1.6.20 program=aqua registry=standard
INFO[0000] copying an executable file                    aqua_version= env=darwin/arm64 file_name=reviewdog package_name=reviewdog/reviewdog package_version=v0.14.1 program=aqua registry=standard
INFO[0000] copying an executable file                    aqua_version= env=darwin/arm64 file_name=golangci-lint package_name=golangci/golangci-lint package_version=v1.49.0 program=aqua …
```
=> feat(cp): support copying all packages

pkg/checksum/type.go, pkg/checksum/type_test.go, pkg/controller/updatechecksum/update.go, pkg/installpackage/checksum.go
AS IS
```json
{
"checksums": {
"github_archive/github.com/b3nj5m1n/xdg-ninja/v0.2.0.1": "f4f9ab4500e7cf865ff8b68c343537e27b9ff1e6068cb1387e516e608f77cec8"
}
}
```
TO BE
```json
{
"checksums": [
{
"id": "github_archive/github.com/b3nj5m1n/xdg-ninja/v0.2.0.1",
"checksum": "f4f9ab4500e7cf865ff8b68c343537e27b9ff1e6068cb1387e516e608f77cec8",
"algorithm": "sha256"
}
]
}
```
The current format doesn't have the checksum algorithm.
The current default checksum algorithm is `sha512`, but when this will be changed, the configuration file will be broken.
To solve the problem, the new format has the checksum algorithm.
Additionally, the value is not a atring but a object, so we can add new fields in future keeping the compatibility.
=> fix: change the structure of aqua-checksums.json

pkg/installpackage/checksum.go
Close https://github.com/aquaproj/aqua/issues/1289
If package type is `github_archive`, `param.AssetName` is empty.
`filepath.Base("")` returns `"."`.
=> fix: fix assetName

.github/workflows/integration-test.yaml, pkg/cli/generate.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/generate/generate.go, pkg/controller/generate/read_pkg_file.go
Close https://github.com/aquaproj/aqua/issues/1352
`aqua generate` supports specifying the package version. The package version is optional.
e.g.
```console
$ aqua g cli/cli
- name: cli/cli@v2.18.1
$ aqua g cli/cli@v2.0.0
- name: cli/cli@v2.0.0
```
The option `-pin` is added to `aqua generate` command.
This option is useful to prevent the package from being updated by Renovate.
```console
$ aqua g -pin cli/cli
- name: cli/cli
version: v2.18.1
$ aqua g -pin cli/cli@v2.0.0
- name: cli/cli
version: v2.0.0
```
=> feat(generate): support specifying version

pkg/controller/generate/generate.go
Close #1388
This bug came from https://github.com/aquaproj/aqua/commit/0c87e2cc50a40a76d3177743e846cc782365409c .
Affected versions: [v1.23.0](https://github.com/aquaproj/aqua/releases/tag/v1.23.0)
Fixed.
```console
$ aqua g foo
FATA[0000] aqua failed                                   aqua_version= env=darwin/arm64 error="unknown package" package_name="standard,foo" program=aqua
```
=> fix(generate): fix a panic

pkg/cosign/verify.go, pkg/installpackage/cosign.go
Assets of Cosign for windows/arm64 aren't released.
=> fix: skip installing cosign and verify with cosign in windows/arm64

pkg/config/registry/package_info.go
Remove `slsa_provenance: null` from the output of `aqua gr`
=> fix: set omitempty to slsa_provenance

pkg/config/aqua/registry.go, pkg/config/registry/package_info.go, pkg/domain/github_content.go, pkg/domain/github_release.go, pkg/download/download.go, pkg/download/github_content.go, pkg/download/github_release.go, pkg/download/util.go
If `private` is true, aqua skips downloading assets via HTTP requests because requests always fail.
Close #1466
Close #1468
=> feat: support a new field `private` for private packages and registries

tests/cosign/aqua.yaml
Verification with Cosign frequently failed.
```
Error: verifying blob [/tmp/482325480]: getting Fulcio roots: error getting targets: error getting target fulcio.crt.pem by usage: open /home/runner/.sigstore/root/targets/fulcio.crt.pem: no such file or directory
main.go:62: error during command execution: verifying blob [/tmp/482325480]: getting Fulcio roots: error getting targets: error getting target fulcio.crt.pem by usage: open /home/runner/.sigstore/root/targets/fulcio.crt.pem: no such file or directory
```
=> ci: remove flaky test

pkg/checksum/error.go, pkg/checksum/registry.go, pkg/controller/generate/generate.go, pkg/controller/install/install.go, pkg/controller/list/list.go, pkg/controller/list/list_test.go, pkg/controller/updatechecksum/update.go, pkg/controller/which/which.go, pkg/controller/wire_gen.go, pkg/install-registry/install.go, pkg/install-registry/install_test.go, pkg/installpackage/installer.go
Close #1491
aqua.yaml
```yaml
checksum:
enabled: true
```
aqua-checksums.json
```json
{
"checksums": [
{
"id": "registries/github_content/github.com/aquaproj/aqua-registry/v3.114.0/registry.yaml",
"checksum": "b5b922c4d64609e536daffec6e480d0fed3ee56b16320a10c38ae12df7f045e8b20a0c05ec66eb28146cee42559e5e6c4e4bc49ce89ffe48a5640999cc6248bd",
"algorithm": "sha512"
}
]
}
```
If the checksum is invalid, the installation of registries would fail.
```
ERRO[0000] install the registry                          actual_checksum=b5b922c4d64609e536daffec6e480d0fed3ee56b16320a10c38ae12df7f045e8b20a0c05ec66eb28146cee42559e5e6c4e4bc49ce89ffe48a5640999cc6248be aqua_version= env=darwin/arm64 error="check a registry's checksum: checksum is invalid" exe_name=starship …
```
=> feat: support verifying Registries' checksums

pkg/checksum/registry.go, pkg/checksum/type.go, pkg/controller/updatechecksum/update.go, pkg/controller/updatechecksum/update_test.go, pkg/controller/wire_gen.go, pkg/domain/github_content.go, pkg/install-registry/install.go
=> fix(update-checksum): fix a bug that registries' checksums are pruned by `-prune` option

.github/workflows/release.yaml, renovate.json5
> Invalid ref: 68bad40844440577b33778c9f29077a3388838e9. Expected ref of the form refs/tags/vX.Y.Z
- https://github.com/slsa-framework/slsa-github-generator/issues/722
=> ci: stop slsa-github-generator pinning because slsa-github-generator doesn't support pinning

pkg/installpackage/proxy.go, renovate.json5
Verify checksums of [aqua-proxy](https://github.com/aquaproj/aqua-proxy) to prevent aqua-proxy from being tampered.
Checksums are hardcoded to aqua.
```
$ aqua i -l
INFO[0000] download and unarchive the package            aqua_version= env=darwin/arm64 package_name=aqua-proxy package_version=v1.1.3 program=aqua registry=
FATA[0002] aqua failed                                   actual_checksum=278120EFDA95AB505E43A2863393F254749D4229B4A49E5B3FB941245F6760A3 aqua_version= env=darwin/arm64 error="checksum is invalid" expected_checksum=B88992BF317AF50109C32533B05E0BF19E1FB71489F18BBFE3AD3D1D0ACEE74B program=aqua
```
=> fix: verify aqua-proxy's checksum

pkg/controller/generate/output/insert.go
https://github.com/aquaproj/aqua/blob/42caed5179f5aca04148dcb3b15c0ec30e641630/pkg/controller/generate/output/insert.go#L32
A newline is duplicated.
https://github.com/goccy/go-yaml/blob/6cdefc42e112ac71cbe316e1eed264ea62f58e25/ast/ast.go#L570
```go
// String all documents to text
func (f *File) String() string {
docs := []string{}
for _, doc := range f.Docs {
docs = append(docs, doc.String())
}
if len(docs) > 0 {
return strings.Join(docs, "\n") + "\n"
} else {
return ""
}
}
```
:o: 1.10.0
:o: 1.20.0
:o: 1.25.0
:x: 1.25.2
:x: 1.26.0
:x: 1.30.3
In v1.25.2, goccy/go-yaml was updated from v1.9.6 to v1.9.8.
https://github.com/aquaproj/aqua/compare/v1.25.0...v1.25.2#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
- https://github.com/aquaproj/aqua/pull/1429
- …
=> fix(generate): remove a newline

pkg/cosign/verify.go, pkg/exec/exec.go, pkg/exec/mock.go
- https://github.com/aquaproj/aqua/issues/1554
If `cosign verify-blob` failed and the output includes the message `resource temporarily unavailable`, aqua retries `cosign verify-blob` at most 4 times.
Each wait time is randomized and at most 1 second.
e.g.
```console
$ tflint --help
INFO[0000] download and unarchive the package            aqua_version= env=darwin/arm64 exe_name=tflint exe_path=/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/terraform-linters/tflint/v0.44.1/tflint_darwin_arm64.zip/tflint package=terraform-linters/tflint package_name=terraform-linters/tflint package_version=v0.44.1 program=aqua registry=standard
INFO[0001] downloading a checksum file                   aqua_version= env=darwin/arm64 exe_name=tflint …
```
=> feat: retry the verification by Cosign

pkg/cosign/verify.go, pkg/installpackage/cosign.go, pkg/installpackage/installer.go
When aqua tries to install cosign multiple times in parallel, it would cause the error.
Cosign should be installed only once, and another goroutines should wait until the installation finishes.
=> fix: lock installing cosign

pkg/checksum/type.go
=> fix: skip setting checksum if the key already exists

aqua-checksums.json, aqua.yaml, pkg/checksum/registry.go, pkg/installpackage/checksum.go
```
time="2023-02-02T01:22:11Z" level=error msg="install the registry" actual_checksum=603942e90f42411891411460a1ff5ceac0e9ae9233cc828b7cab5d8bedd76d90bbe5476e6744c50de6827869da2641562990fe649dd5f872cb98397b2e2c30e6 aqua_version=1.32.2 env=linux/amd64 error="check a registry's checksum: checksum is invalid" expected_checksum=603942E90F42411891411460A1FF5CEAC0E9AE9233CC828B7CAB5D8BEDD76D90BBE5476E6744C50DE6827869DA2641562990FE649DD5F872CB98397B2E2C30E6 program=aqua registry_name=standard
```
This bug occurs when a Registry is installed and the Registry's checksum in `aqua-checksums.json` is uppercase,
because the calculated checksum is lowercase.
This bug raises by https://github.com/aquaproj/aqua/releases/tag/v1.32.2 , because this release makes checksums uppercase.
=> fix: fix a bug Registry's checksums are compared without normalization

pkg/config-finder/config_finder.go
- https://github.com/aquaproj/aqua/issues/1595
The following files are supported.
- aqua.yaml
- aqua.yml
- .aqua.yaml
- .aqua.yml
- aquaproj/aqua.yaml
- aquaproj/aqua.yml
- .aquaproj/aqua.yaml
- .aquaproj/aqua.yml
- Update aqua to v1.33.0 or later
- Move files
```sh
mkdir aquaproj
cp -R aqua aquaproj/imports
mv aqua.yaml aqua-checksums.json aquaproj
rm -R aqua
vi aquaproj/aqua.yaml # Fix `import` if you change the directory name
cp aqua-policy.yaml aquaproj/policy.yaml # `cp` instead of `mv` to prevent an error
```
- Fix `AQUA_POLICY_CONFIG`
- After fixing `AQUA_POLICY_CONFIG`, remove the old policy file
```sh
rm aqua-policy.yaml
```
=> feat: support aggregating configuration files in one directory

pkg/config-finder/config_finder.go
- https://github.com/aquaproj/aqua/issues/1595#issuecomment-1416714321
- https://github.com/aquaproj/aqua/pull/1615
I reconsidered the directory name.
I think `aqua` is better than `aquaproj`, because `aqua` is simple and easy to understand.
I had a concern the conflict with other projects, but the conflict would rarely occur.
Even if the directory name conflicts, aqua still works.
And you can also separate directory by the prefix `.`.
```
aqua # For another project
.aqua # For aqua
```
=> fix: change directory name from aquaproj to aqua

pkg/checksum/checksum.go, pkg/cli/generate_registry.go, pkg/cli/runner.go, pkg/config/package.go, pkg/config/registry/checksum.go, pkg/config/registry/package_info.go, pkg/config/registry/replacements.go, pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/generate_internal_test.go, pkg/controller/generate-registry/interface.go, pkg/controller/generate-registry/version_overrides.go, pkg/controller/generate/output/output.go, pkg/controller/wire.go, pkg/controller/wire_gen.go
https://github.com/aquaproj/aqua/issues/1655
Add command line options `--deep` and `--out-testdata` to `aqua gr` command.
- `--deep`: Generate `version_overrides`
- `--out-testdata`: Output testdata to a file
⚠️ `--deep` option calls GitHub API per GitHub Release. So if there are a lot of GitHub Releases, many GitHub API are called and GitHub API rate limiting may occur.
```console
$ aqua gr --deep --out-testdata pkg.yaml cloudspannerecosystem/wrench
```
Result: https://github.com/aquaproj/generate-registry-deep/actions/runs/4263618160
```yaml
packages:
repo_owner: cloudspannerecosystem
repo_name: wrench
description: wrench - Schema management tool for Cloud Spanner -
asset: wrench_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz
checksum:
asset: …
```
=> feat(generate-registry): support generating version_overrides and testdata

pkg/checksum/parser.go, pkg/installpackage/checksum.go, pkg/installpackage/checksum_internal_test.go
- https://github.com/aquaproj/aqua/issues/1692
e.g.
```
ERRO[0005] Checksum isn't found in a checksum file. Checksum file content:
237db2e5a4fa7525362c012e94c8a76b36a73d138ac7950cc1c07d862a7cc74a  github-comment_5.0.3_windows_amd64.tar.gz
48e49e0b5f1b3af4b5be13b7031bfb38d856259f09f3582e4f67bcae4b357429  github-comment_5.0.3_linux_arm64.tar.gz
58a32e01623ea00fc3650ffb149f724d3e76a06b2aa5237bb128da138ee79359  github-comment_5.0.3_linux_amd64.tar.gz
621a03cd09ee7eb57d9a00cdfb8c2fe70232b64db070c74122df5a0d7f26ae02  github-comment_5.0.3_darwin_arm64.tar.gz
b893acb1bef079724017590a115bc1447208ea92b0c1fdf8563c6dfc1ef19ff0  github-comment_5.0.3_darwin_amd64.tar.gz
c1a3e184957850e333e24ee437a14b55c8ea78d2e190be71c0f72b0eac0e09d7  github-comment_5.0.3_windows_arm64.tar.gz  aqua_version= …
```
=> feat: output the content of a checksum file when it fails to parse a checksum file

pkg/installpackage/find_src.go, pkg/installpackage/installer.go
- https://github.com/aquaproj/aqua/issues/1668
e.g.
```console
$ aqua i --test
ERRO[0000] check file_src is correct                     aqua_version= env=darwin/arm64 error="check file_src is correct: exe_path isn't found: stat /Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/Azure/aks-engine/v0.76.0/aks-engine-v0.76.0-darwin-amd64.tar.gz/aks-engine: no such file or directory" file_name=aks-engine package_name=Azure/aks-engine package_version=v0.76.0 program=aqua registry=standard
ERRO[0000] executable files aren't found
Files in the unarchived package:
aks-engine-v0.76.0-darwin-amd64/aks-engine
aqua_version= env=darwin/arm64 package_name=Azure/aks-engine package_version=v0.76.0 program=aqua registry=standard
ERRO[0000] install the package …
```
=> feat: show the content of the unarchived directory if the executable file isn't found

pkg/checksum/error.go, pkg/checksum/parser.go, pkg/checksum/parser_test.go
Cherry pick a commit from https://github.com/aquaproj/aqua/pull/1577 .
https://github.com/aquaproj/aqua/pull/1577 has not breaking change, so we can release this feature in aqua v1.
- https://github.com/aquaproj/aqua/pull/1577
```console
$ git cherry-pick e15e93b1f51f26600cf61a3b4eb90d5d0e07d6c1
```
=> feat: support default checksum parser

pkg/controller/which/which.go
- https://github.com/aquaproj/aqua/issues/1818
=> fix: add a link to the document "command is not found"

.github/workflows/macos-test.yaml, .github/workflows/wc-integration-test.yaml, .github/workflows/windows-test.yaml, pkg/controller/install/install.go
- https://github.com/aquaproj/aqua/pull/1844/commits/a4a4382902d1be73e0db8a2d3ff78248517f66b7
- https://github.com/aquaproj/aqua/actions/runs/4650825549/jobs/8230051988#step:46:45
--
```console
$ cd tests/main
$ AQUA_GLOBAL_CONFIG=$PWD/aqua-global.yaml aqua cp -a
INFO[0000] copying an executable file                    aqua_version=2.3.0 env=darwin/arm64 file_name=kind package_name=kubernetes-sigs/kind package_version=v0.18.0 program=aqua registry=standard
INFO[0000] copying an executable file                    aqua_version=2.3.0 env=darwin/arm64 file_name=terracognita package_name=cycloidio/terracognita package_version=v0.8.3 program=aqua registry=standard
INFO[0000] copying an executable file                    aqua_version=2.3.0 env=darwin/arm64 file_name=cmdx …
```
=> fix: Fix a bug that `aqua i -a` and `aqua cp -a` don't read policy files properly

pkg/config/package.go
This method seems to have been used for "go" type package.
=> refactor: remove an unused method "RenderDir"

pkg/config/const.go, pkg/config/package.go, pkg/template/render.go
- https://github.com/aquaproj/aqua/issues/1774
=> feat: support omitting `{{.Format}}` in Asset and provide the variable `AssetWithoutExt`

pkg/config/const.go, pkg/config/package.go, pkg/template/render.go
Reverts aquaproj/aqua#1853
If the file extension is different from `format`, there is an issue.
- https://github.com/aquaproj/aqua-registry/issues/11365
=> Revert "feat: support omitting `{{.Format}}` in Asset and provide the variable `AssetWithoutExt`"

.github/workflows/release.yaml
https://github.com/suzuki-shunsuke/go-release-workflow/releases/tag/v0.4.1-1
=> ci: update go-release-workfllow to v0.4.1-1

pkg/checksum/type.go
Fix a panic `fatal error: concurrent map writes`
=> fix: get a write lock before writing a map

.github/workflows/debug-with-action-tmate.yaml
Follow up #1921
https://github.com/aquaproj/aqua/actions/runs/4868678091/jobs/8682358685
```
Run gh pr checkout "1919"
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
Error: Process completed with exit code 1.
```
=> chore: set github token

pkg/config/package.go, pkg/installpackage/find_src.go, pkg/installpackage/installer.go
- https://github.com/aquaproj/aqua/issues/1904
```
ERRO[0000] check file_src is correct                     aqua_version= env=windows/amd64 error="check file_src is correct: get file_src: CreateFile C:\\Users\\runneradmin\\AppData\\Local\\aquaproj-aqua\\pkgs\\github_release\\github.com\\kubernetes-sigs\\kustomize\\kustomize\\v4.5.7\\kustomize_v4.5.7_windows_amd64.tar.gz\\hoge: The system cannot find the file specified." exe_name=kustomize file_name=kustomize package=kubernetes-sigs/kustomize/version_prefix package_name=kubernetes-sigs/kustomize/version_prefix package_version=kustomize/v4.5.7 program=aqua registry=local
ERRO[0000] executable files aren't found
Files in the unarchived package:
kustomize.exe
aqua_version= env=windows/amd64 exe_name=kustomize …
```
=> fix: list package contents if the executable file isn't found in Windows

go.mod, go.sum, pkg/controller/generate-registry/generate.go
Hi, 
I made a few aqua fixes. I'm not familiar with Golang, so I may be wrong, but please review.
Also, I skipped creating an Issue because the scope of the fix seemed small. Instead I wrote details in this PR.
Remove emoji from the description displayed when `aqua gr [package]` is executed.
Registry style guide says "Don't use emojis as much as possible"
https://aquaproj.github.io/docs/develop-registry/registry-style-guide/#dont-use-emojis-as-much-as-possible
But, when I ran `aqua gr [package]` command that displayed emoji.
```console
$ aqua gr hmarr/codeowners
packages:
repo_owner: hmarr
repo_name: codeowners
description: 🔒 Command line tool and Go library for CODEOWNERS files
asset: codeowners_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
format: tar.gz …
```
=> feat(generate-registry): remove emoji from description

pkg/checksum/parser.go
- https://github.com/aquaproj/aqua/issues/1956
=> fix: fix a bug the default checksum parser can't extract the checksum if the checksum has a prefix "*"

pkg/controller/install/install_test.go, pkg/installpackage/installer.go, pkg/installpackage/installer_test.go, pkg/installpackage/proxy.go
Close #1872
Move the symbolic link for `aqua-proxy` from `$AQUA_ROOT_DIR/bin/aqua-proxy` to `$AQUA_ROOT_DIR/aqua-proxy`.
=> feat: move aqua-proxy from bin dir to AQUA_ROOT_DIR

pkg/cli/root_dir.go, pkg/cli/runner.go
```console
$ aqua help root-dir
NAME:
aqua root-dir - Output the aqua root directory (AQUA_ROOT_DIR)
USAGE:
aqua root-dir [command options] [arguments...]
DESCRIPTION:
Output the aqua root directory (AQUA_ROOT_DIR)
e.g.
$ aqua root-dir
/home/foo/.local/share/aquaproj-aqua
$ export "PATH=$(aqua root-dir)/bin:PATH"
OPTIONS:
--help, -h  show help
```
=> feat: add root-dir command

pkg/cli/generate.go, pkg/cli/runner.go, pkg/config/aqua/config.go, pkg/config/package.go, pkg/controller/generate/generate.go
https://github.com/orgs/aquaproj/discussions/2027
With -detail (-d) option, aqua outputs additional information such as description and link.
```console
$ aqua g -detail cli/cli
- name: cli/cli@v2.2.0
description: GitHub’s official command line tool
link: https://github.com/cli/cli
```
The environment variable `AQUA_GENERATE_WITH_DETAIL` is also available.
```sh
export AQUA_GENERATE_WITH_DETAIL=true
```
=> feat: add -detail option to "generate" command

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.2.1
=> chore: update aqua-proxy v1.2.0 to v1.2.1

pkg/cli/info.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/info/info.go, pkg/controller/wire.go, pkg/controller/wire_gen.go
e.g.
```console
$ aqua info
{
"version": "",
"commit_hash": "",
"os": "darwin",
"arch": "arm64",
"pwd": "/Users/(USER)/Documents/aqua/info",
"root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
"env": {
"AQUA_GLOBAL_CONFIG": "/Users/(USER)/repos/src/github.com/aquaproj/aqua-registry/aqua-all.yaml",
"GITHUB_TOKEN": "(masked)"
},
"config_files": [
{
"path": "/Users/(USER)/Documents/aqua/info/aqua/aqua.yaml"
}
]
}
```
=> feat: add info command

pkg/checksum/type.go, pkg/controller/updatechecksum/update.go
Follow up a bug of https://github.com/aquaproj/aqua/pull/2108
The bug affects only aqua v2.10.0.
=> fix: stop outputting checksum file paths except for aqua update-checksum

go.mod, go.sum, pkg/exec/dmg.go, pkg/exec/exec.go, pkg/exec/pkg.go
Go 1.20 supports Cmd.Cancel, and Cmd.WaitDelay.
=> refactor: replace suzuki-shunsuke/go-timeout to exec.CommandContext, Cmd.Cancel, and Cmd.WaitDelay

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.2.2
=> chore: update aqua-proxy to v1.2.2

.goreleaser.yml
https://goreleaser.com/deprecations/#brewstap
=> chore(goreleaser): replace `tap` with `repository`

pkg/config/registry/config.go, pkg/controller/generate/generate.go, pkg/controller/list/list.go
Change the log level if packages don't have names.
If aqua supports new package types and add packages to Standard Registry,
old aqua outputs warnings because it can't get package names correctly.
But if those packages aren't used, aqua don't need to output the warning.
To suppress the warning, this pull request changes the log level to debug.
=> fix: change the log level from warn to debug

README.md, logo/README.md, logo/aqua_horizontal_white.svg
Display README logo optimized for dark/light backgrounds.
This is particularly helpful for transparent PNG/SVG images.
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
If appreciated, I can make the same changes to main `README.md`  of the project.
=> chore: dark/light mode logo

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.2.3
=> chore: update aqua-proxy to v1.2.3

pkg/cli/remove.go, pkg/controller/generate/cargo.go, pkg/controller/generate/controller.go, pkg/controller/generate/generate.go, pkg/controller/generate/generate_test.go, pkg/controller/generate/github_release.go, pkg/controller/generate/github_tag.go, pkg/controller/generate/read_pkg_file.go, pkg/controller/remove/controller.go, pkg/controller/remove/remove.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/fuzzyfinder/const.go, pkg/fuzzyfinder/finder.go, pkg/fuzzyfinder/finder_internal_test.go, pkg/fuzzyfinder/version_selector.go, pkg/fuzzyfinder/version_selector_internal_test.go
Close #2251
Added a command line option `-i` to the command `remove`.
```console
$ aqua rm -i
```
If this option is set, you can select packages with a fuzzy finder to uninstall packages.
The fuzzy finder shows all packages, which include not installed packages.
=> feat(remove): support selecting packages with fuzzy finder

pkg/config/registry/supported_envs.go
This bug was introduced in aqua v1.30.0.
- https://github.com/aquaproj/aqua-registry/pull/15753#issuecomment-1736716809
I found an original issue and a pull request.
- https://github.com/aquaproj/aqua/issues/1512
- https://github.com/aquaproj/aqua/pull/1514
> Add darwin/arm64 to supported_envs if rosetta2 is enabled.
> Currently, we have to add darwin/arm64 explicitly even if rosetta2 is enabled.
I remembered the intention.
But this should be applied only if darwin/amd64 is included in `supported_envs`.
=> fix: fix a bug that supported_envs gets true even if darwin isn't supported on darwin/arm64

pkg/installpackage/proxy.go
- https://github.com/aquaproj/aqua-proxy/releases/tag/v1.2.4
=> chore: update aqua-proxy to v1.2.4

pkg/asset/exclude.go, pkg/asset/format.go, pkg/asset/format_test.go, pkg/asset/generate.go, pkg/unarchive/unarchive.go
=> feat: enable to use short file extensions in `format`

json-schema/registry.json, pkg/config/registry/package_info.go, pkg/config/registry/supported_envs.go
Close #2132
This pull request adds a new field `build` to Registry settings.
This enables to install packages by `go_install` or `go_build` on platforms where prebuilt binaries aren't published.
This is an example usage of the new field `build`.
```yaml
packages:
repo_owner: suzuki-shunsuke
repo_name: tfcmt
asset: tfcmt_{{.OS}}_{{.Arch}}.{{.Format}}
format: tar.gz
supported_envs:
- linux
build:
type: go_build
files:
- name: tfcmt
src: ./cmd/tfcmt
dir: tfcmt-{{trimV .Version}}
```
`supported_envs` is `linux` because prebuilt binaries are published only for linux.
On platforms other than `supported_envs`, aqua installs tfcmt by `go_build`.
`go_install` is also available.
```yaml
build:
type: go_install
path: github.com/suzuki-shunsuke/tfcmt/v4/cmd/tfcmt
```
If …
=> feat: support using go_install or go_build if the asset for the platform isn't released in GitHub Releases

json-schema/registry.json, pkg/config/registry/package_info.go
`build.type` is optional.
```yaml
build:
enabled: false
```
=> docs: fix JSON Schema

pkg/cli/update_aqua.go
`update-aqua` is too long.
```
aqua update-aqua
```
So I add an alias `upa`.
```
aqua upa
```
=> feat(update-aqua): add an alias `upa` to the command `update-aqua`

pkg/cli/generate_registry.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/generate_internal_test.go, pkg/controller/generate-registry/version_overrides.go
Close https://github.com/aquaproj/aqua/issues/2351
The behaviour of `generate-registry` command was changed.
The command gets all GitHub Releases by default to generate `version_overrides`.
The option `--deep` is deprecated. The option has no meaning anymore. The option is kept only for the compatibility.
The option will be removed at aqua v3.
The option `--limit (-l)` is added. This option takes an integer, which is the maximum number of releases.
e.g.
```sh
aqua gr --limit 100
```
=> feat(generate-registry): get all GitHub Releases by default

go.mod, go.sum
To fix the bug, update go-findconfig to v1.2.0.
- https://github.com/suzuki-shunsuke/go-findconfig/releases/tag/v1.2.0
- https://github.com/suzuki-shunsuke/go-findconfig/pull/617
Directory structure
```
/workspace/
aqua.yaml
foo/ # current directory
aqua/
aqua.yaml
```
Run `aqua i`.
```sh
aqua i
```
aqua installs packages with `/workspace/aqua.yaml` and `/workspace/foo/aqua/aqua.yaml`.
aqua installs packages with only `/workspace/foo/aqua/aqua.yaml`, and ignores `/workspace/aqua.yaml`.
=> fix: fix a bug that aqua stops searching configuration files if files are located in either aqua or .aqua directory

pkg/installpackage/aqua.go
To update aqua to v2.16.2 or later from aqua v2.16.0 or earlier by `aqua update-aqua` command on Windows, you need to update aqua to v2.16.1 once.
```sh
aqua update-aqua v2.16.1
aqua update-aqua
```
=> fix: change the format to zip on Windows at v2.16.2

.github/workflows/wc-integration-test.yaml
Recently, we are facing GitHub API rate limiting.
I guess this is because the behavior of `aqua gr` was changed and a lot of API are called in the integration test. So I fixed the integration test.
And I replaced `${{github.token}}` to GitHub App token.
=> ci: use GitHub App and reduce the number of GitHub API calls

pkg/controller/updatechecksum/update.go
Close #2467
Fixed a bug that the calculated checksum is wrong.
- https://github.com/aquaproj/aqua/issues/2467
=> fix(update-checksum): copy an asset to a temporal file to calculate the checksum correctly

pkg/policy/config_finder.go
- https://github.com/orgs/aquaproj/discussions/2476
=> fix(policy): fix a bug that the Git Repository root's policy file doesn't work well in working trees

pkg/versiongetter/cargo.go, pkg/versiongetter/cargo_test.go, pkg/versiongetter/fuzzy_getter.go, pkg/versiongetter/general.go, pkg/versiongetter/github_release.go, pkg/versiongetter/github_release_test.go, pkg/versiongetter/github_tag.go, pkg/versiongetter/github_tag_test.go, pkg/versiongetter/mock_github_release.go, pkg/versiongetter/mock_version_getter.go, pkg/versiongetter/version_getter.go
Solve issue mentioned in #2460 
- Log processing time for GitHub API
- Log GitHub API Rate Limit info after retrieving the version.
- Log errors when command encounters err.
```sh
$ aqua g cli/cli
INFO[0003] GitHub API rate limit info                    aqua_version= env=linux/amd64 gh_rate_limit=60 gh_rate_remaining=59 program=aqua repo=cli/cli
INFO[0003] Retrieve pkg version(s) in 3.734309466s       aqua_version= env=linux/amd64 program=aqua repo=cli/cli
- name: cli/cli@v2.38.0
$ aqua g -s cli/cli
INFO[0007] Retrieve pkg version(s) in 5.211403407s       aqua_version= env=linux/amd64 gh_rate_limit=60 gh_rate_remaining=58 program=aqua repo=cli/cli
- name: cli/cli@v2.38.0
$ aqua g -s -l -1 cli/cli
INFO[0011] Retrieve pkg version(s) in 5.069310084s       aqua_version= env=linux/amd64 …
```
=> Feat: Log enhancement for command generate and update

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.2.5
=> chore: update aqua-proxy to v1.2.5

pkg/download/error.go, pkg/download/github_content.go, pkg/download/github_content_test.go, pkg/github/github.go, pkg/github/mock.go
Close #2713
Use the API [RepositoriesService.DownloadContents](https://pkg.go.dev/github.com/google/go-github/v60/github#RepositoriesService.DownloadContents) instead of [RepositoriesService.GetContents](https://pkg.go.dev/github.com/google/go-github/v60/github#RepositoriesService.GetContents) to download large files from GitHub.
=> fix: use DownloadContents API instead of GetContents to download large files

.github/workflows/wc-integration-test.yaml, pkg/cli/list.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/list/interface.go, pkg/controller/list/list.go, pkg/controller/list/list_installed.go
Add command line options `-installed` and `-all (-a)` to the command `list`.
If `-installed` is set, only installed packages are outputted.
```console
$ aqua list -installed
standard,rhysd/actionlint,v1.6.27
standard,suzuki-shunsuke/cmdx,v1.7.4
standard,sigstore/cosign,v1.13.2
standard,suzuki-shunsuke/ghalint,v0.2.9
standard,int128/ghcp,v1.13.2
standard,golangci/golangci-lint,v1.56.2
standard,goreleaser/goreleaser,v1.24.0
standard,reviewdog/reviewdog,v0.17.1
```
By default, global configuration files are ignored.
If `-a` is set, packages in global configuration files are also outputted.
```console
$ aqua list -installed -a
standard,rhysd/actionlint,v1.6.27
standard,suzuki-shunsuke/cmdx,v1.7.4
standard,sigstore/cosign,v1.13.2
standard,suzuki-shunsuke/ghalint,v0.2.9 …
```
=> feat(list): support outputting installed packages

pkg/controller/generate-registry/version_overrides.go, pkg/versiongetter/github_release.go, pkg/versiongetter/github_tag.go
Close #2354
Change the logic to get the latest version as the following.
1. Get a latest release and 30 most recent releases by GitHub API
2. Try to convert them to semver
3. Compare them and get the latest release
prelease versions are ignored unless all releases are prelease versions.
=> fix: improve the logic to get the latest version

pkg/controller/initcmd/init.go
Tools like `yamllint` by default set two spaces from content to comment:
https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
Output the yaml comment for renvoate to pass yamllint.
=> fix(yaml): Fix spaces before comments

pkg/install-registry/install.go
Close #2829
If it failed to read a registry JSON file, aqua failed. In that case, users have to remove the file themselves.
This commit improves the behavior so that aqua can handle broken regsistry JSON files well.
If it fails to read a registry JSON file, aqua removes the file, reads a registry YAML file, and recreates a registry JSON file, and continues the process.
aqua.yaml
```yaml
registries:
- type: standard
ref: v4.160.0  # renovate: depName=aquaproj/aqua-registry
packages:
```
Break a registry json file.
```sh
echo "" > ~/.local/share/aquaproj-aqua/registries/github_content/github.com/aquaproj/aqua-registry/v4.160.0/registry.yaml.json
```
Without this change, aqua fails.
```console
$ aqua which gh
ERRO[0000] install the registry                          aqua_version=2.27.1 …
```
=> fix: improve handling of broken registry JSON files

pkg/config/checksum.go
- https://github.com/aquaproj/aqua-registry/issues/22170#issuecomment-2073573908
I've confirmed the bug was solved.
- https://github.com/aquaproj/aqua-registry/issues/22170#issuecomment-2073573908
```
aqua upc
```
```json
{
"checksums": [
{
"id": "go_build/github.com/alpkeskin/mosint/v2.3.1",
"checksum": "C4D72E482B85570A1A73776EEF47E993B5F8FA6C204E0B1CAA794E4DF4F13521",
"algorithm": "sha256"
},
{
"id": "registries/github_content/github.com/aquaproj/aqua-registry/v4.164.0/registry.yaml",
"checksum": "FA1425688665781E57A2DDED9F1695D7BD4D90439D3A00BE78DE8CF2F90BF54D",
"algorithm": "sha256"
}
]
}
```
=> fix(checksum): fix a bug that a checksum id of go_build type package is empty

pkg/installpackage/aqua.go
- https://github.com/orgs/aquaproj/discussions/2510
- https://stackoverflow.com/questions/1211948/best-method-for-implementing-self-updating-software
=> fix: fix a bug that update-aqua fails on Windows

go.mod, pkg/config-reader/go_version_file.go, pkg/config-reader/reader.go, pkg/config/aqua/config.go, tests/main/aqua.yaml
- https://github.com/orgs/aquaproj/discussions/2609#discussioncomment-8066126
Close #2730
From Go 1.21, the version of Go is decided by go directive in go.mod or go.work.
e.g.
```
module github.com/aquaproj/aqua/v2
go 1.22.3
```
This can cause an issue that the version of Go may be different from the version defined in aqua.yaml.
And we need to define go version in two places.
To solve the issue, this pull request enables aqua to get the version of go from go directive in go.mod or go.work.
You can specify the path to go.mod or go.work by a field `go_version_file`.
e.g.
```yaml
packages:
- name: golang/go
go_version_file: go.mod
```
Then you can define go version only in go.mod or go.work.
> [!CAUTION]
> The version of Go must be a semver x.y.z.
> You can't omit a patch version.
=> feat: add an option `go-version-file`

pkg/controller/info/info.go
- Link to the issue: fixes #2731
On windows, [`user.Current().Username` returns a string with domain and user concatenated](https://github.com/golang/go/blob/1667dbd7be0da5e75a25f14c339c859ed2190b43/src/os/user/lookup_windows.go#L180-L188). This seems to be called as [down-level logon name](https://learn.microsoft.com/en-us/windows/win32/secauthn/user-name-formats#down-level-logon-name).
This PR makes the domain part to be trimmed, so that the username is masked when running the info command.
=> fix(info): mask username on Windows

pkg/controller/generate/output/insert.go
=> Fix a bug that `aqua g -i` fails if aqua.yaml doesn't have the field `packages`

go.mod
urvave/cli/v2 v2.27.3 is out.
https://github.com/urfave/cli/releases/tag/v2.27.3
- https://github.com/aquaproj/aqua/pull/3023
=> chore: stop using replace directive

.github/workflows/wc-integration-test.yaml, pkg/cli/remove.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/remove/controller.go, pkg/controller/remove/remove.go, pkg/controller/wire.go, pkg/controller/wire_gen.go
Add a command line option `-mode (-m)` to the sub command `remove`.
By default, `aqua remove` command removes only packages from the `pkgs` directory and doesn't remove links from the `bin` directory.
You can change this behaviour by specifying the `-mode` flag.
The value of `-mode` is a string containing characters `l` and `p`.
The order of the characters doesn't matter.
```sh
aqua rm -m l cli/cli # Remove only links
aqua rm -m pl cli/cli # Remove links and packages
```
=> feat: support removing links

pkg/controller/remove/remove.go
This PR resolves #3136
When running the command `aqua remove {cmd}` for a command that exists in the system but is not defined in aqua.yaml, a nil panic occurs. This happens because the code attempts to reference `findResult.Package`, which is `nil` in this case, causing the panic.
https://github.com/aquaproj/aqua/blob/9eff9747af84ae6c77164fd929dee2629b5cfb73/pkg/controller/remove/remove.go#L167
`findResult` is returned from `controller/which/which.go`, where Package is nil in some case.
https://github.com/aquaproj/aqua/blob/fc24ef902cda24f9a190427415e582bf51397129/pkg/controller/which/which.go#L50-L54
=> (cmd/remove) Handle panic error when package is not found, #3136

.github/workflows/wc-integration-test.yaml, json-schema/aqua-yaml.json, pkg/config/aqua/config.go, pkg/controller/cp/controller.go, pkg/controller/cp/copy.go, pkg/controller/which/which.go, pkg/installpackage/check_file.go, pkg/installpackage/link.go, tests/aliases/aqua.yaml
=> feat: allow command aliases

json-schema/registry.json, pkg/config/registry/package_info.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/versiongetter/fuzzy_getter.go, pkg/versiongetter/general.go, pkg/versiongetter/go.go, pkg/versiongetter/goproxy/client.go
This pull request adds a new field `go_version_path` to registry.
e.g.
```yaml
packages:
- name: _go/sigsum.org/sigsum-go#cmd/sigsum-key
type: go_install
path: sigsum.org/sigsum-go/cmd/sigsum-key
go_version_path: sigsum.org/sigsum-go
```
If this field is set, `aqua g` and `aqua up` commands gets available versions from [Go Module Proxy](https://proxy.golang.org/).
=> feat: get versions from Go Proxy

pkg/cli/completion/command.go
- Link to the issue: https://github.com/aquaproj/aqua/issues/3294
Three fixes are included in this PR.
The current help text suggests adding the completion settings in `.bash_profile` and `.zprofile`, but `.bash_profile` and `.zprofile` are loaded only in login shell sessions. They are not loaded in (non-login) interactive sessions started inside the login shells, and thus the completion would be disabled in non-login interactive sessions.
**Actual**
```console
$ cat .bash_profile
if command -v aqua &> /dev/null; then
source <(aqua completion bash)
fi
$ bash
$ complete -p aqua
<nothing is output>
```
**Expected**
```console
$ cat .bashrc
if command -v aqua &> /dev/null; then
source <(aqua completion bash)
fi …
```
=> fix: improve the completion settings suggested in `aqua completion --help`

pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/generate_internal_test.go
```sh
aqua gr crates.io/dd-rust-license-tool
```
Before:
```yaml
packages:
- name: crates.io/dd-rust-license-tool
type: cargo
repo_owner: DataDog
repo_name: rust-license-tool
description: A tool for creating the `LICENSE-3rdparty.csv` file for DataDog open-source Rust projects.
crate: dd-rust-license-tool
```
After:
```yaml
packages:
- name: crates.io/dd-rust-license-tool
type: cargo
repo_owner: DataDog
repo_name: rust-license-tool
description: A tool for creating the `LICENSE-3rdparty.csv` file for DataDog open-source Rust projects
crate: dd-rust-license-tool
```
=> fix(generate-registry): format description of cargo packages

.github/workflows/wc-integration-test.yaml, pkg/controller/generate/output/insert.go, tests/insert/aqua.yaml, tests/insert/expect.yaml
=> fix: fix a bug that aqua g -i removes comments in packages

go.mod, go.sum, pkg/controller/generate/output/insert.go
- https://github.com/aquaproj/aqua/pull/3325
- https://github.com/goccy/go-yaml/pull/570
- https://github.com/goccy/go-yaml/releases/tag/v1.15.7
=> chore: update goccy/go-yaml to 1.15.7

pkg/cli/update/command.go, pkg/controller/update/package.go, pkg/controller/update/registry.go
Close #3393
https://aquaproj.github.io/docs/guides/package-tag/
=> feat(update): support filtering updated packages using package tags

pkg/cli/initcmd/command.go, pkg/config-finder/config_finder.go, pkg/config-finder/config_finder_test.go, pkg/controller/initcmd/init.go
This pull request adds a command line option `-d` to `aqua init` command.
```sh
aqua init -d # Create a directory `aqua` and create `aqua/aqua.yaml`
```
Furthermore, this pull request fixes the logic to check if configuration files already exist.
`aqua init` skips creating a configuration file if configuration files already exist.
=> feat(init): add an option `-d` and fix the duplication check

.github/workflows/wc-integration-test.yaml, .golangci.yml, pkg/config-reader/update.go
This is a bug of aqua [v2.44.0](https://github.com/aquaproj/aqua/releases/tag/v2.44.0).
=> fix(update): fix a bug that `aqua up` fails if `import_dir` is used

.github/workflows/wc-integration-test.yaml, cmd/gen-jsonschema/main.go, json-schema/aqua-generate-registry.json, pkg/cli/genr/command.go, pkg/cli/util/util.go, pkg/config/package.go, pkg/controller/generate-registry/confg.go, pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/generate_internal_test.go, pkg/controller/generate-registry/version_overrides.go, pkg/expr/asset_filter.go, tests/gr-config/aqua-generate-registry.yaml
Close #3561
This pull request enables you to filter versions and assets when running `aqua gr` command.
Scaffold configuration file `aqua-generate-registry.yaml`:
```sh
aqua gr -init <package name>
```
aqua-generate-registry.yaml:
```yaml
package: <package name>
version: not (Version matches "-rc$")
asset: not (Asset matches "-cli")
```
The fields `version` and `asset` are expr's expressions.
https://expr-lang.org/docs/language-definition
These expressions must return boolean.
If they return true, the version and asset are used.
Otherwise, they are ignored.
```yaml
- version:
- inputs:
- Version: A package version
- Available functions:
- semver
- semverWithVersion
- asset
- inputs:
- Asset: An asset name
``` 
For instance, `version: not (Version matches "-rc$")` excludes versions with …
=> feat(generate-registry): support config file and filter versions and assets

.github/workflows/wc-integration-test.yaml
=> ci: specify config to prevent cosign from being installed before testing

json-schema/registry.json, pkg/config/registry/github_cli.go, pkg/installpackage/verify_github_artifact_attestation.go
Close #3581
This pull request enables aqua to support not only `signer-workflow` but also `signer_workflow`.
At aqua v3, we will remove the support of `signer-workflow`.
=> fix: support signer_workflow too

README.md
- Link to the issue: https://github.com/orgs/aquaproj/discussions/2124
At LayerX, we use aqua in various scenarios. Thank you for developing such a wonderful CLI tool :)
=> docs: add LayerX to who-uses-aqua

pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/group.go
This adds support for generating cosign configs for checksum files in `gr`.
Lightly tested, may have bugs. But a happy path exists: https://github.com/aquaproj/aqua-registry/pull/33234
- Link to the issue: https://github.com/aquaproj/aqua-registry/issues/32207#issuecomment-2661324286
=> feat: generate checksum cosign config

pkg/controller/generate-registry/generate.go
For example in https://github.com/sigstore/cosign/releases/tag/v2.4.3
=> fix(gr): use cosign cert if sig is keyless, not pubkey even if available

json-schema/registry.json, pkg/config/registry/cosign.go, pkg/cosign/verify.go
Close https://github.com/aquaproj/aqua/issues/3682
https://aquaproj.github.io/docs/reference/registry-config/cosign/
This pull request adds a field `.cosign.bundle` to support `cosign verify-blob`'s `--bundle` option.
This is same with cosign's other settings such as `key`, `certificate`, and `signature`.
e.g. https://github.com/cert-manager/cmctl/releases/tag/v2.1.1
```yaml
cosign:
bundle:
asset: checksums.txt.cosign.bundle
```
=> feat: support cosign veryf-blob's --bundle option

.github/workflows/wc-integration-test.yaml, pkg/minisign/exec.go, pkg/minisign/package.go
Close #3633
Looks good.
https://github.com/aquaproj/aqua/actions/runs/14263508431/job/39980128707?pr=3721
```
WARN[0000] minisign doesn't support this environment     aqua_version= env=linux/arm64 package_name=bufbuild/buf package_version=v0.53.0 program=aqua registry=standard
WARN[0000] minisign doesn't support this environment     aqua_version= env=linux/arm64 package_name=bufbuild/buf package_version=v1.51.0 program=aqua registry=standard
```
=> fix: fix a panic on the platform where minisign isn't supported

json-schema/registry.json, pkg/config/registry/slsa_provenance.go, pkg/installpackage/verify_slsa.go, pkg/slsa/exec.go
Close #3613
```yaml
slsa_provenance:
asset: multiple.intoto.jsonl
source_tag: "-"
```
If `source_tag` is `-`, `--source-tag` isn't set.
=> feat: support disabling slsa-verifier's --source-tag

pkg/cli/completion/bash.go, pkg/cli/completion/zsh.go
- use --generate-shell-completion instead of --generate-bash-completion
see also: https://github.com/urfave/cli/blob/main/docs/v3/examples/completions/shell-completions.md#customization
> The default shell completion flag (--generate-shell-completion) is defined
=> fix: bash and zsh completion command generation

pkg/checksum/checksum.go
These are typically cosign bundles, example in
https://github.com/cert-manager/cmctl/releases/tag/v2.1.1
=> fix(checksum): don't treat *.bundle as checksum

pkg/cli/completion/command.go, pkg/cli/completion/fish.go, pkg/cli/runner.go, pkg/cli/util/util.go
Close #3769
```sh
cmdx i
~/go/bin/aqua fish shell completion
```
<details>
<summary>output</summary>
```
function __fish_aqua_no_subcommand --description 'Test if there has been any subcommand yet'
for i in (commandline -opc)
if contains -- $i init help h install i help h generate g help h update-aqua upa help h update-checksum upc help h update up help h completion bash help h zsh help h fish help h help h which help h info help h remove rm help h vacuum help h cp help h policy allow help h deny help h init help h help h init-policy help h exec help h list help h generate-registry gr help h root-dir help h
return 1
end
end
return 0
end
complete -c aqua -n '__fish_aqua_no_subcommand' -f -l log-level -r -d 'log level'
complete -c aqua -n '__fish_aqua_no_subcommand' -f -l config -s c -r -d …
```
=> fix: fix fish completion

aqua/aqua-policy.yaml, json-schema/registry.json, pkg/config/registry/github_cli.go, pkg/ghattestation/exec.go, pkg/ghattestation/verifier.go, pkg/installpackage/verify_github_artifact_attestation.go, tests/cosign/aqua.yaml
Closes https://github.com/aquaproj/aqua/issues/3793
Caveat: untested, but I suppose this could work.
- Link to the issue: https://github.com/aquaproj/aqua/issues/3793
---
e.g. https://github.com/pkdindustries/soulshack
https://github.com/pkdindustries/soulshack/blob/f625a32a1dd503edc0980eb081a2eae249cab578/.github/workflows/go.yml#L94
```yaml
github_artifact_attestations:
signer_workflow: pkdindustries/soulshack/.github/workflows/go.yml
predicate_type: https://in-toto.io/attestation/release/v0.1
```
=> feat(ghattestation): non-default predicate type support

pkg/config/registry/registry.go, pkg/controller/which/which.go, pkg/install-registry/install_test.go
```console
$ hyperfine --warmup 3 "/Users/shunsukesuzuki/go/bin/aqua which mkghtag" "/Users/shunsukesuzuki/.local/share/aquaproj-aqua/internal/pkgs/github_release/github.com/aquaproj/aqua/v2.50.0/aqua_darwin_arm64.tar.gz/aqua which mkghtag"
Benchmark 1: /Users/shunsukesuzuki/go/bin/aqua which mkghtag
Time (mean ± σ):     445.4 ms ±  36.2 ms    [User: 502.7 ms, System: 170.1 ms]
Range (min … max):   423.5 ms … 518.1 ms    10 runs
Warning: The first benchmarking run for this command was significantly slower than the rest (518.1 ms). This could be caused by (filesystem) caches that were not filled until after the first run. You are already using the '--warmup' option which helps to fill these caches before the actual benchmark. You can either try to increase the warmup count further or …
```
=> perf: cache a map of packages

go.mod, go.sum, pkg/cli/generate/command.go, pkg/cli/genr/command.go, pkg/cli/initcmd/command.go, pkg/cli/list/command.go, pkg/cli/remove/command.go, pkg/cli/token/command.go, pkg/cli/upc/command.go, pkg/cli/update/command.go, pkg/cli/vacuum/command.go, pkg/cli/which/command.go, pkg/controller/rmtoken/controller.go, pkg/controller/rmtoken/rm.go, pkg/controller/settoken/controller.go, pkg/controller/settoken/set.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/github/github.go, pkg/github/github_test.go, pkg/keyring/keyring.go
This pull request enables you to manage a GitHub Access token using secret store such as [Windows Credential Manager](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0), [macOS Keychain](https://en.wikipedia.org/wiki/Keychain_(software)), and [GNOME Keyring](https://wiki.gnome.org/Projects/GnomeKeyring).
1. Configure a GitHub Access token by `aqua token set` command:
```console
$ aqua token set
Enter a GitHub access token: # Input GitHub Access token
```
or you can also pass a GitHub Access token via standard input:
```sh
echo "<github access token>" | aqua tokn set -stdin
```
2. Enable the feature by setting the environment variable `AQUA_KEYRING_ENABLED`:
```sh
export AQUA_KEYRING_ENABLED=true
```
Note that if the environment …
=> feat: support managing a GitHub access token using Keyring

go.sum, pkg/controller/generate-registry/controller.go, pkg/controller/generate-registry/generate_internal_test.go, pkg/controller/wire_gen.go
Even though `InitializeGenerateRegistryCommandController` accepts stdout as an argument, the passed stdout was not correctly used. 
https://github.com/aquaproj/aqua/blob/d772eb40ac35ab8f4cef96dab82de6a7209d5d89/pkg/cli/genr/command.go#L145
This PR fixed the problem.
Note that I used `go generate ./...` to generate wire_gen.go file. It seems it produces needless diff since it uses the latest wire code.
I don't know what wire version was used previously, so I just left it as is. We may want to consider managing wire with aqua config?
=> bind given stdout correctly for generate-registry controller

go.mod, go.sum, pkg/github/github.go
Close #3931
https://github.com/suzuki-shunsuke/go-retryablehttp/releases/tag/v0.7.8-1
diff: https://github.com/suzuki-shunsuke/go-retryablehttp/commit/547881255cebe9de69e56cd00ad54c04bd103205
Before
```console
$ go install github.com/aquaproj/aqua/v2/cmd/aqua@a8c17eb9e35245bdf6fc9505e75c86d225a87049
go: downloading github.com/aquaproj/aqua/v2 v2.53.1
go: github.com/aquaproj/aqua/v2/cmd/aqua@a8c17eb9e35245bdf6fc9505e75c86d225a87049 (in github.com/aquaproj/aqua/v2@v2.53.1):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
```console
$ go install github.com/aquaproj/aqua/v2/cmd/aqua@v2.53.1
go: …
```
=> fix: stop replacing hashicorp/go-retryablehttp

pkg/download/github_release.go, pkg/github/github.go
Reverts aquaproj/aqua#4019
The issue was resolved by GitHub side.
So the change #4019 is unnecessary.
=> Revert "fix: Add AQUA_DOWNLOAD_USER_AGENT variable and set User-Agent to GitHub Release downloads"

pkg/installpackage/check_file.go, pkg/installpackage/link.go
- [x ] Read [CONTRIBUTING.md](https://github.com/aquaproj/aqua/blob/main/CONTRIBUTING.md)
- [x ] Read [OSS Contribution Guide](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/README.md)
- [x ] [Write a GitHub Issue before creating a Pull Request](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/README.md#create-an-issue-before-creating-a-pull-request)
- [x ] [All commits are signed](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md)
- [x ] [Avoid force push](https://github.com/suzuki-shunsuke/oss-contribution-guide?tab=readme-ov-file#dont-do-force-pushes-after-opening-pull-requests)
- [x ] Do only one thing …
=> fix(cp): adds missing .exe on windows

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.2.12
=> chore: update aqua-proxy to v1.2.12
