aquaproj/aqua

docs/config.md
=> docs: describe template variables

aqua.yaml, docs/config.md, pkg/controller/config.go, pkg/controller/exec.go, pkg/controller/install.go, pkg/controller/install_proxy.go, tutorial/README.md, tutorial/aqua.yaml
=> fix: rename `artifact` to `asset`

aqua.yaml
=> chore: remove aqua from aqua.yaml

aqua.yaml, docs/config.md, pkg/controller/config.go, pkg/controller/download.go, pkg/controller/exec.go, pkg/controller/install.go, pkg/controller/install_proxy.go, tutorial/README.md, tutorial/aqua.yaml
=> fix: rename `repository` to `registry`

pkg/controller/exec.go
=> feat: support global install

renovate.json
=> chore: fix renovate fileMatch

.github/workflows/renovate-config-validator.yaml, pkg/controller/install_proxy.go, renovate.json5
Test: https://github.com/suzuki-shunsuke/test-renovate-2/pull/70
=> chore: set up Renovate to update aqua-proxy

renovate.json5
=> chore: fix depNameTemplate

pkg/controller/install_proxy.go
https://github.com/suzuki-shunsuke/aqua-proxy/releases/tag/v0.1.1
=> chore: update aqua-proxy

README.md
https://techblog.szksh.cloud/aqua/
=> docs: add a link to blog written in Japanese

pkg/controller/exec.go
=> fix: check if the file exists before execute the command and add debug log

README.md, pkg/controller/exec.go, pkg/controller/install.go, pkg/controller/lookpath.go, tutorial/README.md, tutorial/aqua.yaml, tutorial/docker-compose.yml
=> feat: create symbolic links to ~/.aqua/bin and remove the local .aqua directory

.goreleaser.yml
=> chore: stop releasing assets for Windows

.github/workflows/test.yml, pkg/controller/exec_internal_test.go
=> test: add test

pkg/cli/install.go, pkg/cli/runner.go, pkg/controller/config.go, pkg/controller/exec.go, pkg/controller/install.go
=> feat: add the test flag to install command

pkg/controller/install.go
=> fix: fix install test

pkg/controller/config.go, pkg/controller/exec.go, pkg/controller/install.go
=> feat: check if the package info name is unique in the same registry

pkg/controller/install.go, pkg/controller/install_proxy.go, pkg/controller/lookpath.go
=> feat: change the symbolic link to the relative path

pkg/controller/config.go, pkg/controller/registry.go
=> fix: fix inline registry

README.md
=> docs: add slide

README.md, aqua.yaml, docs/config.md, pkg/controller/registry.go, tutorial/aqua.yaml
=> feat: support the `official` registry

README.md, aqua.yaml, docs/config.md, docs/registry.md, pkg/controller/config_test.go, pkg/controller/registry.go, tutorial/README.md, tutorial/aqua.yaml
=> fix: rename `official` to `standard`

README.md
https://techblog.szksh.cloud/aqua-v0.5/
=> docs: add the link to blog

README.md, aqua.yaml, renovate.json5
https://github.com/suzuki-shunsuke/aqua-renovate-config
=> chore: use aqua-renovate-config

README.md, docs/renovate.md
https://github.com/suzuki-shunsuke/aqua-renovate-config
=> docs: add the document about Renovate

pkg/controller/config.go, pkg/controller/generate.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go
https://github.com/suzuki-shunsuke/aqua-registry/pull/64
https://github.com/ktr0731/go-fuzzyfinder
```
$ aqua g
```
=> feat: add link and description to packages

README.md
=> docs: add Note about Windows

README.md, docs/config.md
https://dev.to/suzukishunsuke/aqua-declarative-cli-version-manager-1ibe
=> docs: add a link to blog

pkg/controller/config.go, pkg/controller/registry.go
=> feat: disable config strict mode

pkg/controller/install_packages.go
=> fix: when the registry isn't found, exit with non zero

README.md
https://github.com/suzuki-shunsuke/versioning-policy/blob/v0.1.0/POLICY.md
=> docs: clarify the versioning policy

pkg/controller/config.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go
Related: #249 
Add some template variables
* Version
* ArchiveType
Deprecate some template variables
* Package
* PackageInfo
* File
=> feat: add template variables

pkg/controller/config.go, pkg/controller/controller.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go
* `OS` => `GOOS`
* `Arch` => `GOARCH`
* `Replacements.OS` => `OS`
* `Replacements.Arch` => `Arch`
=> feat: rename template variables

README.md
https://github.com/int128/aqua-action
=> docs: add a link to int128/aqua-action

pkg/controller/exec.go, pkg/controller/install_packages.go
=> feat: separate the goroutine to create symbolic link and install package

aqua.yaml, docs/config.md, docs/lazy-install.md, pkg/controller/config.go, pkg/controller/config_test.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go, registry.yaml
Close #268 
#249 #250
The following Template Variables are removed.
* Package
* PackageInfo
* File
=> feat: remove deprecated template variables

README.md
* https://github.com/suzuki-shunsuke/aqua/releases/tag/v0.6.0
* https://github.com/suzuki-shunsuke/aqua/pull/255
=> docs: you can't select version in `aqua g`

pkg/controller/install_packages.go
Close #51
Follow up https://github.com/suzuki-shunsuke/aqua-registry/pull/155
=> feat: add the executable permission to the owner if he doesn't have

cmd/aqua/main.go, pkg/cli/install.go, pkg/controller/config.go, pkg/controller/controller.go, pkg/controller/download.go, pkg/controller/exec.go, pkg/controller/generate.go, pkg/controller/install_packages.go, pkg/controller/install_proxy.go, pkg/controller/registry.go
=> feat: add version in log

go.mod, go.sum, pkg/controller/config.go, pkg/controller/config_test.go, pkg/controller/controller.go, pkg/controller/github_release_package.go, pkg/controller/http_package.go, pkg/controller/install_proxy.go, pkg/controller/template.go
#298
Parse templates when it is needed.
It prevents from unneeded parsing.
=> perf: lazy build of the template

README.md
https://techblog.szksh.cloud/aqua-global-configs/
=> docs: add a link to the blog post

docs/usage.md
=> docs: update usage

README.md, aqua.yaml, docs/config.md, pkg/controller/config.go, pkg/controller/config_internal_test.go, pkg/controller/config_test.go
=> feat: support to add the package version to the package name

README.md, aqua.yaml, docs/config.md, pkg/controller/config.go, pkg/controller/generate.go
=> feat: use standard registry by default

.github/workflows/integration-test.yaml, aqua.yaml, docs/registry_config.md, pkg/controller/config.go, pkg/controller/download.go, pkg/controller/download_github.go, pkg/controller/github_content_package.go
=> feat: support a new package type "github_content"

.github/workflows/integration-test.yaml, aqua.yaml, docs/registry_config.md, pkg/controller/config.go, pkg/controller/download.go, pkg/controller/error.go, pkg/controller/generate.go, pkg/controller/github_archive_package.go
Close #261
e.g.
```yaml
- type: github_archive
repo_owner: tfutils
repo_name: tfenv
description: Terraform version manager
files:
- name: tfenv
src: tfenv-{{trimV .Version}}/bin/tfenv
- name: terraform
src: tfenv-{{trimV .Version}}/bin/terraform
```
=> feat: support the package type `github_archive`

aqua-global-2.yaml, aqua-global.yaml, aqua/reviewdog.yaml, renovate.json5
https://github.com/suzuki-shunsuke/aqua-renovate-config#parameterize-filematch
=> refactor: use Renovate preset `github>suzuki-shunsuke/aqua-renovate-config:file`

.github/workflows/integration-test.yaml, pkg/controller/controller.go, pkg/controller/download.go, pkg/controller/download_github.go
=> feat: add debug log

pkg/controller/download.go, pkg/controller/download_github.go, pkg/controller/download_url.go, pkg/controller/download_url_internal_test.go, pkg/controller/exec.go, pkg/controller/generate.go, pkg/controller/install_packages.go, pkg/controller/registry.go
https://github.com/suzuki-shunsuke/aqua/issues/391
=> feat: download github_content registry without GitHub API

README.md, docs/config.md, pkg/controller/controller.go, pkg/controller/download.go, pkg/controller/download_github.go
=> feat: make GitHub access token optional

README.md, logo/README.md
=> docs: add description about logo

README.md
https://techblog.szksh.cloud/slides/aqua/introduction-5min
=> docs: add a link to slide

README.md, logo/README.md
Follow up #403 #405
I have generated the code with [Choose a license](https://creativecommons.org/choose/?lang=en).
http://creativecommons.org/licenses/by-nc-nd/4.0/
=> docs: add the license of logo

README.md
https://suzuki-shunsuke.github.io/slides/aqua/introduction-5min
URL was changed.
=> docs: fix a link

.github/ISSUE_TEMPLATE/Bug_Report.md
=> chore: fix issue template

aqua.yaml, pkg/controller/exec.go, pkg/controller/install_packages.go, pkg/controller/package_condition.go, pkg/controller/package_info.go, pkg/controller/version_constraint.go
=> feat: support skipping to install packages on unsupported platform

pkg/controller/config.go, pkg/controller/package_info.go
=> fix: override `rosetta2` by `version_overrides`

pkg/controller/install_packages.go
Close #455
Close #456
When the package isn't supported on the environment, aqua forgets to dequeue maxInstallChan.
This bug affected `aqua v0.8.1, v0.8.2, v0.8.3`.
https://github.com/aquaproj/aqua/pull/439
=> fix: dequeue maxInstallChan properly

pkg/controller/version_constraint.go
Close #462
Add the template functions `trimPrefix` and `semverWithVersion`.
e.g.
```yaml
repo_owner: kubernetes-sigs
repo_name: kustomize
asset: 'kustomize_{{trimPrefix "kustomize/" .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
version_constraint: 'semverWithVersion(">= 4.2.0", trimPrefix(Version, "kustomize/"))'
version_overrides:
- version_constraint: 'semverWithVersion("< 4.2.0", trimPrefix(Version, "kustomize/"))'
rosetta2: true
```
=> feat: add template functions

pkg/controller/install.go, pkg/controller/install_packages.go, pkg/controller/install_proxy.go
=> feat: update aqua-proxy automatically

pkg/cli/init.go, pkg/cli/runner.go, pkg/controller/init.go
=> feat: add a init command

pkg/controller/exec.go
=> fix: use logerr

.github/workflows/integration-test.yaml, pkg/controller/controller.go, pkg/controller/generate.go, pkg/controller/package_info.go, pkg/controller/version_constraint.go, pkg/controller/version_filter.go, tests/registry.yaml
=> feat: support filtering version in `aqua g`

pkg/controller/generate.go
=> fix: exclude prerelease

pkg/controller/install_packages.go
Close #511
```yaml
registries:
- type: standard
ref: v0.13.1
packages:
- name: cli/cli@v2.0.0
- name: cli/cli@v2.0.0
- name: cli/cli@v2.0.0
- name: cli/cli@v2.0.0
- name: cli/cli@v2.0.0
```
`aqua i` failed.
```console
$ aqua -v
aqua version 0.8.13 (f99fbccd103127a3eab411c58af506ef18fb4290)
$ aqua i
INFO[0000] download and unarchive the package            aqua_version=0.8.13 package_name=cli/cli package_version=v2.0.0 program=aqua registry=standard
INFO[0000] download and unarchive the package            aqua_version=0.8.13 package_name=cli/cli package_version=v2.0.0 program=aqua registry=standard
INFO[0000] download and unarchive the package            aqua_version=0.8.13 package_name=cli/cli package_version=v2.0.0 program=aqua registry=standard
INFO[0000] download and unarchive the …
```
=> feat: retry installing a package when it failed to install the package due to `file already exists` error

pkg/controller/install_packages.go
=> feat: add registry_ref in the error log

pkg/controller/exec.go
Close #537
The parallel execution of Lazy Install raises the problem.
e.g.
* actionlint executes shellcheck in parallel per `run` step
* Parallel execution by `xargs -P`, `GNU Parallel`, and so on
=> feat: support retrying

pkg/controller/generate.go
=> fix: fix a trivial bug

pkg/controller/config.go, pkg/controller/config_test.go, pkg/controller/generate.go
https://github.com/aquaproj/aqua/issues/582
=> perf: replace `goccy/go-yaml` to `gopkg.in/yaml.v2` due to the performance issue

pkg/controller/generate.go, pkg/controller/list.go
=> feat: read global config in generate and list command

.goreleaser.yml
* https://goreleaser.com/customization/templates/
* https://goreleaser.com/customization/release/
=> chore(goreleaser): update release header

.cmdx.yaml, cmd/gen-jsonschema/main.go, go.mod, go.sum, json-schema/aqua-yaml.json, json-schema/registry.json, pkg/config/config.go, pkg/config/package_info.go, pkg/config/registry.go, pkg/config/replacements.go, pkg/template/template.go, pkg/version-constraint/package_condition.go, pkg/version-constraint/version_constraint.go, pkg/version-constraint/version_filter.go
* https://github.com/aquaproj/aqua/issues/623
* https://github.com/invopop/jsonschema
Generate JSON Schema from aqua's source code.
```console
$ cmdx js
```
Or
```console
$ go run ./cmd/gen-jsonschema
```
=> feat: generate JSON Schema

.cmdx.yaml, json-schema/aqua-yaml.json, json-schema/registry.json, pkg/config/config.go, pkg/config/package_info.go, pkg/config/package_info_internal_test.go, pkg/config/version_override.go
=> fix: fix JSON Schema

cmd/gen-jsonschema/main.go
=> fix: fix gen-jsonschema

.cmdx.yaml, json-schema/README.md
=> docs: add document about JSON Schema

json-schema/registry.json, pkg/config/config.go, pkg/config/replacements.go
https://github.com/aquaproj/aqua/issues/623#issuecomment-1086582565
=> feat: add enum to JSON Schema of GOOS and GOARCH

pkg/controller/exec/exec.go
=> fix: fix logging

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.0.0
=> chore: update aqua-proxy to v1.0.0

pkg/config/config.go
=> fix: check if alias isn't duplicated

pkg/config/package_info.go
=> refactor: use RenderURL

pkg/config/package_info.go, pkg/controller/generate/generate.go, pkg/version-constraint/bool.go, pkg/version-constraint/error.go, pkg/version-constraint/version_filter.go
https://github.com/aquaproj/aqua/issues/693
=> refactor: replace VersionFilter to string

pkg/config/config.go, pkg/config/config_test.go, pkg/config/package_info.go, pkg/config/package_info_internal_test.go, pkg/config/package_info_test.go, pkg/config/replacements.go, pkg/installpackage/proxy.go, pkg/template/template.go
=> refactor: replace template to string

pkg/config/package_info.go, pkg/config/package_info_internal_test.go, pkg/config/version_override.go
=> fix: copy packageinfo

pkg/controller/exec/exec.go
=> fix: return error in case of the retry limit

pkg/controller/exec/exec_internal_test.go
=> test: fix test

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua/issues/710#issuecomment-1122165719
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.1.0-0
=> chore: update aqua-proxy to v1.1.0-0

go.mod, go.sum, pkg/controller/exec/exec.go
https://github.com/aquaproj/aqua/issues/710
https://github.com/aquaproj/aqua/issues/725
https://github.com/aquaproj/aqua/compare/5ec6e9d4fa2959ef1a47109819de2b4381861541...51af70c2d2233d9eaf41ecf6e8e07cae6c177e7d
=> feat: support AQUA_EXPERIMENTAL_X_SYS_EXEC

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.1.0-1
=> chore: update aqua-proxy to v1.1.0-1

pkg/installpackage/proxy.go
https://github.com/aquaproj/aqua-proxy/releases/tag/v1.1.0
=> chore: update aqua-proxy to v1.1.0

.github/workflows/integration-test.yaml, pkg/controller/generate/generate.go, pkg/controller/list/list.go
=> fix: pass global configuration file paths in list and generate command

json-schema/registry.json, pkg/config/package_info.go
=> docs: add go to package type enums

.github/workflows/integration-test.yaml, json-schema/registry.json, pkg/config/package_info.go, pkg/controller/generate/generate.go, pkg/github/github.go, pkg/github/mock.go, tests/registry.yaml
=> feat: support github_tag

json-schema/registry.json
=> docs: update JSON Schema

pkg/exec/exec.go, pkg/exec/xsys.go, pkg/exec/xsys_windows.go
https://github.com/aquaproj/aqua/issues/850#issuecomment-1153199772
=> fix: stop using "golang.org/x/sys/unix" on Windows

pkg/config-finder/config_finder.go
=> fix: support windows

pkg/config/package.go, pkg/config/package_info_test.go
https://github.com/aquaproj/aqua/issues/850#issuecomment-1153454185
=> feat: set the file extension ".exe" in Windows

pkg/installpackage/proxy.go
=> fix: fix aqua-proxy path for windows

.goreleaser.yml
=> chore: build assets for Windows

pkg/config/package.go, pkg/config/package_info_test.go, pkg/unarchive/unarchive.go, pkg/unarchive/unarchive_test.go
=> feat: add the file extension ".exe" even if ".Format" is empty

pkg/cli/completion.go
=> feat: add the description to completion command

pkg/config/registry/package_info.go, pkg/config/registry/replacements.go
=> fix: support overriding complete_windows_exe

pkg/config/package.go
=> fix: don't add ".exe" in case of github_archive by default

pkg/config/registry/package_info.go, pkg/config/registry/supported_envs.go, pkg/config/registry/supported_envs_test.go, pkg/controller/which/which.go, pkg/installpackage/installer.go
https://github.com/aquaproj/aqua/issues/882
=> feat: add supported_envs

pkg/config/package.go, pkg/config/package_info_test.go, pkg/config/registry/package_info.go, pkg/config/registry/replacements.go, pkg/installpackage/installer.go
https://github.com/aquaproj/aqua/issues/883
https://zenn.dev/shunsuke_suzuki/scraps/6671231c095360
=> feat: support renaming files to add file extensions on Windows

go.mod, pkg/log/log_windows.go
Close #916
It works fine 👍 
Git Bash
PowerShell
Command Prompt
Git Bash
PowerShell
Command Prompt
=> feat: show color on Windows

go.mod, go.sum, pkg/config-reader/reader.go, pkg/config/aqua/config_test.go, pkg/config/registry/registry_test.go, pkg/controller/generate/generate.go, pkg/install-registry/install.go, tests/aqua.yaml, tests/registry.yaml
gopkg.in/yaml.v3 doesn't allow duplicated keys.
https://go.dev/play/p/t0QvRz5t7D3
https://twitter.com/szkdash/status/1540178831637909504
=> chore: revert #918

pkg/cli/generate_registry.go, pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/generate_internal_test.go
=> fix: fix typo

pkg/controller/generate-registry/arch.go
=> fix(generate-registry): set amd64 by default

pkg/controller/generate-registry/generate.go
=> fix(generate-registry): ignore the extension .dmg

pkg/controller/generate-registry/generate.go
=> fix(generate-registry): ignore the file extension .sha256

pkg/controller/generate-registry/generate.go
=> fix(generate-registry): fix format and overrides

pkg/controller/exec/exec.go, pkg/controller/exec/exec_internal_test.go, pkg/controller/exec/exec_test.go, pkg/controller/install/install_test.go, pkg/exec/exec.go, pkg/exec/mock.go, pkg/exec/xsys.go, pkg/exec/xsys_windows.go, pkg/installpackage/installer.go, pkg/installpackage/installer_test.go, pkg/installpackage/proxy_test.go, pkg/installpackage/public.go
=> refactor(exec): return a concrete type instead of interface

pkg/controller/generate/generate.go
=> fix(generate): remove duplicated items

.github/workflows/integration-test.yaml, go.mod, pkg/controller/generate-registry/generate.go
Close #1003
Replace gopkg.in/yaml.v3 to github.com/goccy/go-yaml
=> fix(generate-registry): encode emojis properly

.github/workflows/test.yaml
https://github.com/aquaproj/aqua/runs/7330758825?check_suite_focus=true#step:11:137
```
! [rejected]        v1.17.1             -> v1.17.1  (would clobber existing tag)
```
=> ci: fetch tags forcibly

pkg/template/template.go
=> fix: remove some template functions for security reason

pkg/config/package.go, pkg/controller/generate-registry/generate.go, pkg/util/ext.go
=> fix: wrap filepath.Ext

.github/workflows/integration-test.yaml, pkg/cli/cp.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/cp/controller.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/util/wait.go
=> feat: add cp command

pkg/cli/generate.go, pkg/controller/generate/generate.go, pkg/controller/generate/generate_insert.go
=> feat: add "-o" option to aqua g command

pkg/cli/runner.go, pkg/cli/update_checksum.go, pkg/config/aqua/checksum_enabled.go
Reverts aquaproj/aqua#1118
I merged this pr mistakenly.
=> Revert "feat: enable checksum verification"

pkg/checksum/checksum.go
=> feat: support MD5 for the checksum verification

pkg/asset/generate.go, pkg/asset/type.go
=> fix(generate-registry): set `complete_windows_ext`

pkg/config/aqua/checksum.go, pkg/controller/cp/install.go, pkg/controller/exec/exec.go, pkg/domain/package_installer.go, pkg/installpackage/checksum.go, pkg/installpackage/download.go, pkg/installpackage/error.go, pkg/installpackage/installer.go, pkg/installpackage/installer_test.go
=> feat: support `require_checksum`

pkg/installpackage/checksum.go
=> fix(checksum): fix assetName

pkg/cli/runner.go, pkg/config/aqua/checksum_enabled.go, pkg/controller/initcmd/init.go
- https://github.com/aquaproj/aqua/issues/427
- https://github.com/aquaproj/aqua/pull/1187
=> feat: release checksum verification

pkg/controller/updatechecksum/update.go, pkg/controller/updatechecksum/update_test.go, pkg/domain/package_downloader.go, pkg/download/package.go, pkg/download/package_test.go, pkg/installpackage/download.go, pkg/installpackage/download_internal_test.go
=> fix(updatechecksum): fix the checksum calculated by `-deep` option

pkg/cli/init_policy.go, pkg/cli/runner.go, pkg/controller/initpolicy/init.go, pkg/controller/initpolicy/init_test.go, pkg/controller/wire.go, pkg/controller/wire_gen.go
=> feat: add init-policy command

pkg/config-finder/config_finder.go, pkg/config-finder/config_finder_test.go, pkg/config-reader/reader.go, pkg/config-reader/reader_test.go, pkg/config/aqua/registry.go, pkg/controller/exec/exec_test.go, pkg/controller/generate/generate_test.go, pkg/controller/install/install_test.go, pkg/controller/list/list_test.go, pkg/controller/which/which_test.go, pkg/install-registry/error.go, pkg/policy/config.go, pkg/util/abs.go
=> fix(policy): fix a bug that forbid local registry wrongly

.github/workflows/integration-test.yaml, pkg/controller/generate/generate.go
=> fix(generate): fix a bug of `--pin` option

pkg/config/package.go, pkg/installpackage/download.go
=> feat: support template in go_install package's path attribute

pkg/controller/updatechecksum/update.go, pkg/controller/updatechecksum/update_test.go
=> feat(update-checksum): exclude unrelated files' checksums

.github/workflows/integration-test.yaml, pkg/checksum/type.go, pkg/cli/runner.go, pkg/cli/update_checksum.go, pkg/config/package.go, pkg/controller/updatechecksum/update.go
=> feat(update-checksum): support pruning unused checksums

pkg/checksum/supported_envs.go, pkg/config/aqua/checksum.go, pkg/config/extract.go, pkg/config/registry/supported_envs_test.go, pkg/controller/updatechecksum/update.go, pkg/log/log.go, pkg/runtime/parse.go, pkg/runtime/runtime.go
=> Support excluding unneeded os/arch checksum from aqua-checksums.json

json-schema/registry.json, pkg/checksum/checksum.go, pkg/config/registry/checksum.go
=> feat(checksum): support sha1 algorithm

pkg/controller/exec/exec_test.go, pkg/controller/generate/generate.go, pkg/controller/generate/generate_test.go, pkg/controller/install/install.go, pkg/controller/install/install_test.go, pkg/controller/list/list.go, pkg/controller/list/list_test.go, pkg/controller/updatechecksum/update.go, pkg/controller/updatechecksum/update_test.go, pkg/controller/which/which.go, pkg/controller/which/which_test.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/domain/cosign.go, pkg/installpackage/checksum.go, pkg/installpackage/cosign.go, pkg/installpackage/download.go
=> feat: install cosign lazily

pkg/config/registry/supported_envs.go
Close https://github.com/aquaproj/aqua/issues/1512
=> feat: add darwin/arm64 to supported_envs if rosetta2 is enabled

.github/workflows/release.yaml, .goreleaser.yml, aqua.yaml
=> chore: sign checksum files by Cosign

pkg/installpackage/checksum.go, pkg/installpackage/cosign.go, pkg/installpackage/download.go, pkg/installpackage/installer.go
=> fix: install cosign properly even if AQUA_GOOS and AQUA_GOARCH are set

pkg/config/registry/error.go, pkg/config/registry/version_override.go
=> fix: return error if version doesn't match with all version_constraints

.github/workflows/integration-test.yaml, pkg/config/checksum.go, pkg/config/package.go, pkg/config/registry/package_info.go, pkg/config/registry/version_override.go, pkg/controller/generate/generate.go, pkg/controller/generate/github_release.go, pkg/controller/generate/github_release_internal_test.go, pkg/controller/generate/github_tag.go, pkg/expr/version_constraint.go, pkg/expr/version_constraint_test.go, pkg/expr/version_filter.go, pkg/policy/policy_package.go, pkg/policy/policy_package_test.go, pkg/policy/policy_registry.go, pkg/template/render.go, tests/main/aqua-global.yaml, tests/main/registry.yaml
=> feat: add the field `version_prefix` to package

pkg/cosign/verify.go, tests/cosign/aqua.yaml
=> fix: Get a lock when running Cosign

.github/workflows/integration-test.yaml, pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/interface.go
e.g.
```
aqua gr suzuki-shunsuke/tfcmt@v3.2.4
```
=> feat(generate-registry): support specifying version

.github/workflows/integration-test.yaml, pkg/config-finder/config_finder.go, pkg/config-finder/config_finder_test.go, pkg/config/registry/package_info.go, pkg/config/registry/package_info_test.go, pkg/config/registry/supported_envs.go, pkg/controller/which/which_test.go, pkg/exec/exec.go, pkg/exec/mock.go, pkg/expr/package_condition.go, pkg/expr/package_condition_test.go, pkg/installpackage/installer.go, pkg/installpackage/installer_test.go, pkg/installpackage/public.go, pkg/policy/config_reader.go, tests/main/aqua-global.yaml, tests/main/registry.yaml
=> Revert "breaking changes for v2"

pkg/expr/version_compare.go, pkg/expr/version_constraint.go, pkg/expr/version_filter.go
- https://github.com/aquaproj/aqua/issues/1573
=> feat: change the implementation of semver and semverWithVersion

pkg/slsa/verifier.go
Close https://github.com/aquaproj/aqua/issues/1585
=> fix: retry slsa-verifier when slsa-verifier failed

.github/workflows/test.yaml, aqua-checksums.json, aqua/ghalint.yaml, ghalint.yaml
https://github.com/suzuki-shunsuke/ghalint
=> ci: run ghalint

renovate.json5
https://github.com/suzuki-shunsuke/renovate-config/releases/tag/1.1.3-1
=> chore: test aqua-renovate-config 1.1.3-1

pkg/config/aqua/checksum.go, pkg/installpackage/download.go
https://github.com/aquaproj/aqua/issues/1656
=> fix: change the behaviour of require_checksum

pkg/config/registry/package_info.go, pkg/installpackage/installer.go
- https://github.com/aquaproj/aqua/issues/1684
=> feat: support outputting error message when it failed to install a package

pkg/config/aqua/checksum.go, pkg/controller/cp/controller_test.go, tests/cosign/aqua.yaml, tests/main/aqua.yaml, tests/slsa/aqua.yaml
https://github.com/aquaproj/aqua/issues/1681
=> feat: enable require_checksum by default

json-schema/registry.json
- https://github.com/aquaproj/aqua/issues/1684
=> docs: update JSONSchema. Add error_message

.github/workflows/test.yaml, .github/workflows/windows-test.yaml, pkg/cli/cp.go, pkg/cli/install.go, pkg/cli/runner.go, pkg/config/package.go, pkg/installpackage/aqua_test.go, pkg/installpackage/installer.go, tests/slsa/registry.yaml
BREAKING CHANGE: --test option is removed and the default behaviour is changed
- https://github.com/aquaproj/aqua/issues/1691
=> fix: remove --test option

pkg/controller/cp/controller.go, pkg/controller/exec/exec.go, pkg/installpackage/installer.go
- https://github.com/aquaproj/aqua/issues/1700
=> fix: remove exe_path from log

pkg/download/http.go
- https://github.com/aquaproj/aqua/issues/1704
=> feat: add HTTP status code to error log

renovate.json5
https://github.com/suzuki-shunsuke/renovate-config/releases/tag/2.0.0
=> chore: update renovate-config to 2.0.0

renovate.json5
- https://github.com/suzuki-shunsuke/renovate-config/blob/main/action-go-version.json
=> chore: update go-version

pkg/controller/updatechecksum/update.go
- https://github.com/aquaproj/aqua/issues/1771
=> fix(update-checksum): ignore go_install packages

.github/workflows/test.yaml, pkg/cli/update_checksum.go, pkg/controller/updatechecksum/update.go, pkg/controller/updatechecksum/update_test.go, tests/main/aqua-global.yaml, tests/main/registry.yaml
Close #1769
The default behaviour of `update-checksum` command is changed.
=> feat(update-checksum): change the default behaviour same as --deep option

pkg/cli/install.go
https://github.com/aquaproj/aqua/issues/1691#issuecomment-1475083349
=> fix(install): recover `--test` option

pkg/cli/runner.go, pkg/config/aqua/checksum.go, pkg/config/package.go, pkg/controller/cp/controller.go, pkg/controller/cp/controller_test.go, pkg/controller/cp/install.go, pkg/controller/exec/exec.go, pkg/controller/exec/exec_test.go, pkg/controller/install/install.go, pkg/controller/wire_gen.go, pkg/installpackage/installer.go
- https://github.com/aquaproj/aqua/issues/1781
=> feat(checksum): support configuring require_checksum by the environment variable

pkg/cli/runner.go, pkg/config/package.go, pkg/controller/cp/controller.go, pkg/controller/exec/exec.go, pkg/controller/install/install.go, pkg/policy/config_reader.go
- https://github.com/aquaproj/aqua/issues/1790
=> feat(policy): support disabling policy by environment variable

pkg/checksum/error.go, pkg/checksum/parser.go, pkg/checksum/parser_test.go, pkg/controller/updatechecksum/update.go, pkg/installpackage/checksum.go, pkg/installpackage/checksum_internal_test.go
- https://github.com/aquaproj/aqua/issues/1795
=> fix(checksum): fix a bug that a checksum file content isn't outputted even if the checksum isn't found in the checksum file

.github/workflows/test.yaml, .github/workflows/wc-test-docker-prebuilt.yaml, .github/workflows/wc-test-docker.yaml, .github/workflows/wc-test.yaml, Dockerfile, Dockerfile-prebuilt, cmdx.yaml, renovate.json5, scripts/docker.sh
```console
$ cmdx help docker
NAME:
cmdx docker - Test aqua in a clean container
USAGE:
cmdx docker [command options] [arguments...]
DESCRIPTION:
Build and run a new container and attach a pseudo-TTY.
You can test aqua in a clean environment.
OPTIONS:
--latest, -l  (default: false)
--help, -h    show help
```
=> chore: add a task "docker" to test aqua in a container

pkg/log/log_windows.go
https://github.com/aquaproj/aqua/issues/1889
=> fix: output log to stderr

.github/workflows/debug-with-action-tmate.yaml
- https://github.com/aquaproj/aqua/issues/1920
=> chore: support debugging with action-tmate

.github/workflows/close-issue.yaml
=> ci: fix close-issue

CONTRIBUTING.md
- https://github.com/aquaproj/aqua/issues/1930
=> docs: add a link to issue

.github/workflows/close-issue.yaml
https://github.com/suzuki-shunsuke/issue-close-lock-action
=> ci: use action

pkg/asset/os.go
- https://github.com/aquaproj/aqua-registry/pull/12034#issuecomment-1539233736
=> fix(generate-registry): support "unknown-linux" and "pc-windows"

pkg/controller/generate-registry/generate.go
=> fix(generate-registry): use default checksum parser

pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/version_overrides.go
- https://github.com/aquaproj/aqua/issues/1887
=> feat(generate-registry): parse non semver

pkg/exec/xsys_windows.go
Follow up #2001 
The bug is unreleased.
=> fix: fix compile error on windows

.github/workflows/macos-test.yaml, pkg/asset/format.go, pkg/asset/format_test.go, pkg/asset/os.go, pkg/exec/mock.go, pkg/exec/pkg.go, pkg/installpackage/public.go, pkg/unarchive/dmg.go, pkg/unarchive/pkg.go, pkg/unarchive/unarchive.go, tests/macos/aqua.yaml, tests/macos/registry.yaml
- https://github.com/aquaproj/aqua/issues/1803
=> feat: support pkg format on macOS

pkg/cli/runner.go, pkg/config/package.go, pkg/controller/exec/error.go, pkg/controller/exec/exec.go
- https://github.com/orgs/aquaproj/discussions/2058
=> feat: support disabling Lazy Install

pkg/config/windows_ext.go, tests/main/aqua.yaml
https://github.com/aquaproj/aqua/actions/runs/5570431513/jobs/10174468288
https://github.com/aquaproj/aqua/actions/runs/5570444206/jobs/10174492033
=> fix: fix a bug that file extensions aren't added when packages are installed on Windows

pkg/checksum/type.go
- https://github.com/aquaproj/aqua/issues/2104
=> feat(update-checksum): output created or updated file names

pkg/controller/updatechecksum/update.go, pkg/cosign/verify.go, pkg/download/download.go, pkg/installpackage/download.go, pkg/slsa/verifier.go
- https://github.com/aquaproj/aqua/issues/2188
=> refactor: rename GetReadCloser

pkg/config/checksum.go, pkg/config/checksum_test.go, pkg/controller/updatechecksum/update.go
- https://github.com/aquaproj/aqua/issues/2188
=> refactor: rename Getter (Package.ChecksumIDFromAsset)

pkg/config/aqua/registry.go, pkg/config/aqua/registry_test.go, pkg/config/package.go, pkg/config/package_internal_test.go, pkg/config/package_test.go, pkg/config/windows_ext.go, pkg/controller/which/which.go, pkg/install-registry/install.go, pkg/installpackage/aqua.go, pkg/installpackage/check_file.go, pkg/installpackage/checksum.go, pkg/installpackage/installer.go, pkg/installpackage/proxy.go, pkg/installpackage/verify_cosign.go, pkg/installpackage/verify_slsa.go
- https://github.com/aquaproj/aqua/issues/2188
=> refactor: rename getters

pkg/download/file.go, pkg/installpackage/checksum.go, pkg/installpackage/verify_cosign.go, pkg/installpackage/verify_slsa.go, pkg/unarchive/dmg.go, pkg/unarchive/pkg.go, pkg/unarchive/unarchive.go, pkg/unarchive/unarchiver.go
- https://github.com/aquaproj/aqua/issues/2188
=> refactor: rename Getter (DownloadedFile.GetPath)

json-schema/registry.json, pkg/config/const.go, pkg/config/package.go, pkg/config/registry/package_info.go
- https://github.com/aquaproj/aqua/pull/2310/commits/b52862e7731cbfe9c0ab32cd21427b8ddafd7d42
- https://github.com/aquaproj/aqua/issues/1774
=> feat: support omitting format

pkg/asset/generate.go, pkg/config/checksum_test.go, pkg/config/package.go, pkg/config/package_internal_test.go, pkg/config/package_test.go, pkg/config/registry/override_test.go, pkg/config/registry/package_info.go, pkg/config/registry/package_info_internal_test.go, pkg/config/registry/package_info_test.go, pkg/controller/generate-registry/generate_internal_test.go, pkg/controller/generate-registry/version_overrides.go, pkg/controller/updatechecksum/update_test.go, pkg/install-registry/install_test.go, pkg/installpackage/aqua.go, pkg/installpackage/cosign.go, pkg/installpackage/download_internal_test.go, pkg/installpackage/installer_test.go, pkg/installpackage/proxy.go, pkg/installpackage/slsa_verifier.go
https://github.com/aquaproj/aqua-registry/blob/44ab72989e58174f42c2f7fa9ca94b79e00c0d96/pkgs/vburenin/ifacemaker/registry.yaml#L25
[stop using asset for go_install](https://github.com/aquaproj/aqua/pull/2315/commits/2eeb418fe11843790b83a4b8781e9f5cad0007cd)
=> refactor: change the type of asset

json-schema/registry.json, pkg/config/registry/package_info.go
Fix a bug of JSON Schema.
- https://github.com/aquaproj/aqua/pull/2314
- https://github.com/aquaproj/aqua-registry/pull/16098#issuecomment-1751809222
=> fix: fix JSON Schema to make append_ext optional

json-schema/registry.json, pkg/config/registry/override.go, pkg/config/registry/package_info.go
Close https://github.com/aquaproj/aqua/issues/2318
=> feat: add a new field "envs" to overrides

pkg/versiongetter/github_release.go
- https://github.com/aquaproj/aqua/issues/2354
--
- Use GetLatestRelease API before using ListReleases API
=> fix(versiongetter): Fix getting the latest version

pkg/asset/ast.go, pkg/controller/generate/output/insert.go, pkg/controller/update/ast/package.go, pkg/controller/update/ast/registry.go
Close https://github.com/aquaproj/aqua/issues/2245
=> fix(generate): get key value with ast.StringNode

pkg/cli/generate_registry.go, pkg/cli/runner.go, pkg/config/package.go, pkg/controller/generate-registry/generate.go
=> feat(generate-registry): add an option `-cmd`

pkg/controller/remove/controller.go, pkg/controller/remove/remove.go, pkg/controller/wire.go, pkg/controller/wire_gen.go
e.g.
```sh
aqua rm tfcmt # Remove suzuki-shunsuke/tfcmt
```
=> feat(remove): support removing packages by command names

.goreleaser.yml
- https://github.com/aquaproj/aqua/issues/2400
=> chore: support scoop

pkg/controller/cp/controller.go, pkg/controller/cp/controller_test.go, pkg/controller/exec/controller.go, pkg/controller/install/controller.go, pkg/controller/wire.go, pkg/controller/wire_gen.go, pkg/policy/reader.go
- refactor: remove an unused field
- refactor: define interface by caller
=> refactor: remove an unused field and define interfaces by caller

pkg/controller/cp/controller.go, pkg/controller/cp/install.go, pkg/controller/exec/exec.go, pkg/controller/install/install.go, pkg/installpackage/installer.go
- https://github.com/orgs/aquaproj/discussions/2414
=> fix: fix a bug that AQUA_DISABLE_POLIDY doesn't work

pkg/config/registry/checksum.go, pkg/controller/updatechecksum/update.go, pkg/installpackage/checksum.go
sha256 is enough.
We don't need to use sha512.
=> feat: change the default checksum algorithm to sha256

go.mod, go.sum, pkg/checksum/checksum.go
- https://github.com/aquaproj/aqua/issues/2470
=> refactor: replace the third party library `github.com/codingsince1985/checksum` with standard libraries

pkg/controller/updatechecksum/update.go
Reverts aquaproj/aqua#2469
I merged #2469 to resolve #2467 , but I resolved #2467 by #2472 and #2469 is unnecessary anymore.
https://github.com/aquaproj/aqua/pull/2472#issuecomment-1812023515
=> Revert "fix(update-checksum): copy an asset to a temporal file to calculate the checksum correctly"

pkg/versiongetter/fuzzy_getter.go
- https://github.com/aquaproj/aqua/pull/2461#issuecomment-1817401308
=> fix: copy logE to limit the scope of the side effect

pkg/cli/update.go, pkg/controller/update/update.go, pkg/controller/update/update_test.go
e.g.
```console
$ aqua up gh@v2.27.0
```
=> feat(update): support specifying new package versions

json-schema/registry.json, pkg/config/registry/package_info.go
- https://github.com/aquaproj/aqua-registry/pull/17534#issuecomment-1818597453
=> docs: fix JSON Schema

.github/workflows/wc-integration-test.yaml, pkg/cli/runner.go, pkg/cli/which.go, pkg/config/package.go
- https://github.com/orgs/aquaproj/discussions/2506
=> feat(which): add the command line option `--version`

pkg/installpackage/link.go
- https://github.com/orgs/aquaproj/discussions/2508
- https://www.shellcheck.net/wiki/SC2086
=> fix: fix a bug of bash scripts for Git Bash

.github/DISCUSSION_TEMPLATE/bug-report.yml, .github/DISCUSSION_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/general.yml, .github/workflows/close-issue.yaml
=> Revert "chore: allow users to create issues"

pkg/install-registry/install.go
Close #2517
```console
$ hyperfine -N --warmup 3 '/Users/shunsukesuzuki/.local/share/aquaproj-aqua/internal/pkgs/github_release/github.com/aquaproj/aqua/v2.20.0/aqua_darwin_arm64.tar.gz/aqua exec -- goreleaser -v' '/Users/shunsukesuzuki/go/bin/aqua exec -- goreleaser -v'
Benchmark 1: /Users/shunsukesuzuki/.local/share/aquaproj-aqua/internal/pkgs/github_release/github.com/aquaproj/aqua/v2.20.0/aqua_darwin_arm64.tar.gz/aqua exec -- goreleaser -v
Time (mean ± σ):      75.1 ms ±   0.9 ms    [User: 36.5 ms, System: 12.5 ms]
Range (min … max):    73.6 ms …  78.3 ms    39 runs
Benchmark 2: /Users/shunsukesuzuki/go/bin/aqua exec -- goreleaser -v
Time (mean ± σ):      50.4 ms ±   0.8 ms    [User: 30.1 ms, System: 12.4 ms]
Range (min … max):    48.7 ms …  52.4 ms    58 runs
Summary …
```
=> perf: convert registry to JSON

pkg/config/registry/package_info.go
=> fix: fix the validation that name is required even if no_asset or error_message is set

README.md
Hi, @suzuki-shunsuke 
I have added our case study to "Who uses aqua?" as it has been approved by the public relations staff.
https://github.com/orgs/aquaproj/discussions/2124#discussioncomment-8152619
=> docs: add DeNA

README.md
ref. https://github.com/orgs/aquaproj/discussions/2124
=> docs: add CADDi to who-uses-aqua

pkg/cli/runner.go, pkg/config/package.go, pkg/installpackage/checksum.go, pkg/installpackage/installer.go, pkg/installpackage/verify_cosign.go, pkg/installpackage/verify_slsa.go
=> feat: support disabling cosign and SLSA

pkg/installpackage/cargo.go
Close #2649
- https://github.com/aquaproj/aqua-registry/pull/19544
=> feat(cargo): trim a prefix from cargo package's version

pkg/controller/updatechecksum/update.go
=> fix(update-checksum): ignore cargo and go_install packages properly

pkg/cargo/versions.go, pkg/versiongetter/fuzzy_getter.go
=> fix(cargo): set a User-Agent header to prevent 403 error

pkg/versiongetter/github_release.go
=> fix: stop calling Get latest release API to decrease the number of API call

.goreleaser.yml, pkg/cli/completion.go
=>  Generate shell completion on brew install

pkg/config/checksum.go
Follow up https://github.com/aquaproj/aqua/pull/2833
- https://github.com/aquaproj/aqua/pull/2833
=> fix(checksum): change the checksum id of go_build type package

.github/workflows/wc-enable-auto-merge.yaml
=> ci: use enable-auto-merge-action

.github/workflows/debug-with-action-tmate.yaml, .github/workflows/macos-test.yaml, .github/workflows/test.yaml, .github/workflows/watch-star.yaml, .github/workflows/wc-enable-auto-merge.yaml, .github/workflows/wc-ghalint.yaml, .github/workflows/wc-integration-test.yaml, .github/workflows/wc-status-check.yaml, .github/workflows/wc-test-docker-prebuilt.yaml, .github/workflows/wc-test.yaml, .github/workflows/windows-test.yaml
https://github.com/suzuki-shunsuke/batch-bulk-ghatm/issues/1
=> ci: set timeout-minutes using ghatm

README.md
=> Studist uses aqua

json-schema/registry.json, pkg/config/registry/config.go, pkg/controller/which/which.go, pkg/installpackage/check_file.go
- https://github.com/aquaproj/aqua/issues/3130
```yaml
files:
- name: granted
- name: assume
- name: assumego
src: granted
link: assumego # link is the relative path from src to the symlink
```
=> feat: support changing $0 by symlink

README.md
Thank you for a great tool!
We also use aqua at Connehito.
I especially like the fact that I can manage the CLI tools for each project, not only for each project member's environment, but also for use in GitHub Actions.
I am also happy that Windows is supported!
=> docs: add Connehito to who-uses-aqua

pkg/config/package.go
=> fix: pass vars to render files[].src

CONTRIBUTING.md
- https://github.com/aquaproj/aqua/issues/3311
=> docs: replace discussion with issue

renovate.json5
- https://github.com/aquaproj/aqua/pull/3327
=> chore: stop updating tests/insert by Renovate

pkg/asset/generate.go
=> fix(generate-registry): fix a bug that unused replacements are added

pkg/controller/initcmd/init.go
- https://github.com/aquaproj/aqua/issues/3202
I've confirmed the language server works well on VSCode.
=> feat(init): add a code comment of JSON Schema URL for YAML language servers

cmd/gen-jsonschema/main.go, json-schema/policy.json
- https://github.com/aquaproj/aqua/issues/3202
=> docs: add JSON Schema for policy

json-schema/policy.json, pkg/policy/config.go
- https://github.com/aquaproj/aqua/issues/3202
=> fix: make policy package names optional

pkg/controller/initpolicy/init.go
- https://github.com/aquaproj/aqua/issues/3202
=> feat(policy): add a code comment for JSON Schema of policy files

json-schema/registry.json, pkg/config/registry/cargo.go, pkg/installpackage/cargo.go
- https://github.com/aquaproj/aqua-registry/pull/30442#issuecomment-2566013110
=> feat: support cargo install's `--locked` option

json-schema/registry.json, pkg/config/registry/package_info.go
- https://github.com/aquaproj/aqua-registry/pull/31276#discussion_r1927701350
=> chore: fix supported platforms in JSONSchema

pkg/versiongetter/filter.go, pkg/versiongetter/github_release.go, pkg/versiongetter/github_tag.go
Close #3507
Before:
```
v0.0.1                                                      │ * Bump github.com/aws/aws-sdk-go-v2/config from 1.27.36 to..│
v0.0.2                                                      │ * [add] aqua by @yumafuu in https://github.com/yumafuu/s1m..│
v0.0.3                                                      │                                                             │
v0.1.0                                                      │                                                             │
v0.2.0                                                      │ **Full Changelog**: https://github.com/yumafuu/s1m/compare..│
v0.2.1                                                      │                                                             │
v0.2.2 …
```
=> fix: exclude versions without assets

pkg/config/registry/slsa_provenance.go, pkg/controller/generate-registry/generate.go, pkg/controller/generate-registry/group.go
=> feat(generate-registry): generate slsa_provenance

pkg/asset/generate.go
=> fix(generate-registry): fix complete_windows_ext

json-schema/aqua-generate-registry.json, pkg/controller/generate-registry/confg.go, pkg/controller/generate-registry/init.go, pkg/controller/generate-registry/version_overrides.go, tests/gr-config/aqua-generate-registry.yaml
- https://github.com/aquaproj/aqua/issues/3561
=> fix(generate-registry): rename version to version_filter

pkg/ghattestation/exec.go, pkg/installpackage/verify_github_artifact_attestation.go
=> docs(ghattestation): error message fixes

pkg/controller/generate-registry/group.go, pkg/controller/generate-registry/group_internal_test.go
- https://github.com/aquaproj/aqua-registry/pull/32383#issuecomment-2669892516
=> fix: fix generated test data

pkg/checksum/checksum.go, pkg/cli/exec/command.go, pkg/cli/install/command.go, pkg/cli/update/command.go, pkg/cli/updateaqua/command.go, pkg/policy/reader.go
Refs https://github.com/aquaproj/aquaproj.github.io/pull/1404#issuecomment-2669880130
=> style: output grammar fixes

pkg/controller/generate-registry/group.go, pkg/controller/generate-registry/version_overrides.go
=> fix: fix panic

pkg/controller/generate-registry/group.go
=> fix: fix a panic

pkg/ghattestation/exec.go
=> fix: skip the verification of GitHub Artifact Attestation if the authentication fails

pkg/cosign/verify.go, pkg/installpackage/checksum.go, pkg/minisign/exec.go, pkg/slsa/exec.go
=> style: output spelling fixes

pkg/asset/ast.go, pkg/asset/generate.go, pkg/config-reader/update.go, pkg/config/aqua/config.go, pkg/config/aqua/registry.go, pkg/config/checksum.go, pkg/config/package.go, pkg/config/registry/package_info.go, pkg/controller/generate-registry/insert.go, pkg/controller/generate/output/output.go, pkg/expr/bool.go, pkg/expr/bool_internal_test.go, pkg/expr/version_constraint.go, pkg/expr/version_filter.go, pkg/template/render.go, pkg/template/template.go, pkg/template/template_test.go, pkg/versiongetter/mock_github_tag.go
Modernize spots identified by [gopls' `modernize`](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize), its fixes plus some manual tweaks.
=> refactor: gopls modernize

pkg/controller/generate-registry/group.go
=> fix(generate-registry): fix a panic

pkg/controller/generate-registry/generate.go
For tighter matching.
Refs https://github.com/aquaproj/aqua/pull/3649#discussion_r1996221762
=> feat(cosign): include version in generated cert id regexp

pkg/controller/generate-registry/generate.go
SSIA. Example gr result in https://github.com/aquaproj/aqua-registry/pull/33275
=> feat: generate cosign config for releases with a pubkey

pkg/config/package.go
- https://github.com/aquaproj/aqua/pull/3665#issuecomment-2729260911
=> fix: set AssetWithoutExt

.github/workflows/debug-with-action-tmate.yaml, .golangci.yml, aqua/aqua-checksums.json, aqua/imports/golangci-lint.yaml, pkg/asset/generate.go, pkg/controller/wire.go
- https://github.com/suzuki-shunsuke/batch-task/issues/7
=> chore: Migrate golangci-lint to v2

pkg/cli/runner.go, pkg/cli/util/util.go, pkg/cli/version/command.go
=> fix: fix version command

pkg/asset/os.go
=> fix(generate-registry): add os patterns

.github/workflows/release.yaml, .goreleaser.yml, cmdx.yaml
⚠️ rgo doesn't support Winget yet.
=> ci: use rgo

pkg/controller/generate-registry/group.go, pkg/controller/generate-registry/version_overrides.go
=> fix(gr): fix panic if version isn't semver

.github/workflows/wc-integration-test.yaml, .github/workflows/wc-test.yaml, pkg/cli/runner.go
=> fix: fix `aqua version` command

.github/workflows/wc-integration-test.yaml, aqua/aqua-policy.yaml, json-schema/registry.json, pkg/config/registry/config.go, pkg/installpackage/check_file.go, pkg/installpackage/link.go, tests/pnpm/aqua-checksums.json, tests/pnpm/aqua.yaml, tests/pnpm/package.json
Close #3775
```yaml
files:
- name: pnpm
link: pnpm
hard: true
```
=> feat: support creating hardlinks

.golangci.yml
https://github.com/mvdan/gofumpt#gofumpt
=> chore(golangci-lint): remove gofmt, it's a gofumpt subset

go.mod, go.sum
https://github.com/suzuki-shunsuke/go-retryablehttp-logrus
=> chore: update go-retryablehttp-logrus to v0.0.1

.github/workflows/wc-integration-test.yaml, go.mod, go.sum, pkg/cli/runner.go
Close #3952
- https://github.com/suzuki-shunsuke/urfave-cli-v3-util/releases/tag/v0.0.7
=> fix: fix shell completion

pkg/config/aqua/error.go, pkg/config/aqua/registry.go, pkg/install-registry/install.go
- https://github.com/aquaproj/aqua/issues/4021
=> fix: validate registries when installing them

pkg/ghattestation/exec.go
Close #4035 
Added `GH_HOST=github.com` to the command environment for attestation verification. 
Since Go's `os/exec` gives preference to the last entry when there are duplicate environment variables, this ensures attestation verification always targets `github.com` regardless of existing `GH_HOST` settings.
I've confirmed that this change resolves the error in GHES.
=> fix: force `GH_HOST=github.com` for GitHub Artifact Attestation verification

pkg/ghattestation/exec.go
=> fix: fix a bug that environment variables aren't passed to gh attestation verify
